# Default Docker settings
image: "ghcr.io/lamalab-org/corral-materials:latest"
agent_image: null
port: 8000
auto_find_port: true
host: "0.0.0.0"
network: corral-network
env_container_name: corral-env
agent_container_name: corral-agent
detach: false
output_dir: null
env_args: {}
