import uvicorn
# from tools import  read_lammps_to_string,ase_lammps, pickle_to_lammps,brave_search,wikipedia_search
from tools import run_lammps, bash_command


from corral.base import Environment
from corral.server import create_benchmark_server
import ase


# LAMMPS_TOOLS = [read_lammps_to_string,ase_lammps, pickle_to_lammps,brave_search,wikipedia_search]

LAMMPS_TOOLS = [run_lammps, bash_command]

class LammpsEnvironment(Environment):
    def __init__(self, task_id: str, question: str):
        self.question = question
        super().__init__(task_id)

        # Add multiple tools
        for tool in LAMMPS_TOOLS:
            self.add_tool(tool)

    def get_task_prompt(self) -> str:
        # return f"Solve this  problem, you can use the path {self._path} to read and write if you want : {self.question}"
        return self.question

    def score(self) -> float:
        return 0.0


if __name__ == "__main__":

    # prompt = """

    # Generate a face-centered cubic (FCC) lattice structure for Aluminum (Al) using LAMMPS with a lattice constant of 4.05 angstrom. The simulation should use metal units, define a 5x5x5 simulation box, set periodic boundary conditions to True, and dump the structure in XYZ format to the specified location. Create a directory /Users/chandan21gupta/Desktop/iit_delhi/agent_llms_3/mat-agent-bench/tasks/lammps/lammps/task_2/ and save the following inside it: 

    # 1. The input file used for the simulation. 

    # 2. The output log file generated by LAMMPS. 
    
    # 3. The generated XYZ file containing the lattice structure. 

    # """

    # prompt = '''

    # Generate a face-centered cubic (FCC) lattice structure for Aluminum (Al) using the Atomic Simulation Environment (ASE) package in python with a lattice constant of 4.05 angstrom. The simulation should define a 5x5x5 simulation box, set periodic boundary conditions to True, and dump the structure in XYZ format to the specified location. Create a directory /Users/chandan21gupta/Desktop/iit_delhi/agent_llms_3/mat-agent-bench/tasks/lammps/lammps/task_7/ and save the following inside it: 

    # 1. The Python script used for generating the lattice. 

    # 2. The generated XYZ file containing the lattice structure. 

    # ASE library is already installed in the computing environment.
    # '''

    prompt = '''

    Calculate the cohesive energy of Aluminum (Al) using energy minimization in LAMMPS. The simulation should use metal units, define an FCC (face-centered cubic) lattice with a lattice constant of 4.0 angstrom, employ the EAM potential for atomic interactions, set periodic boundary conditions to True, define a 1x1x1 simulation box, perform the energy minimization using conjugate gradient and dump the final structure in XYZ format to the specified location. Provide the cohesive energy (in eV/atom) as the final output. Create a directory /Users/chandan21gupta/Desktop/iit_delhi/agent_llms_3/mat-agent-bench/tasks/lammps/lammps/task_12/ and save the following inside it: 

    1. The input file used for the simulation. 

    2. The output log file generated by LAMMPS. 

    3. The generated XYZ file containing the structure after energy minimization. 

    The EAM potential file is not available, you can download it from https://www.ctcms.nist.gov/potentials/ .

    '''


    environments = {
        "lammps_1" : LammpsEnvironment("input_1", prompt)
    }

    # Create and run server
    app = create_benchmark_server(environments)

    uvicorn.run(app, host="0.0.0.0", port=8000)
