from corral.base import Tool, ToolArgument
from corral.utils import tool
from typing import Dict
from dotenv import load_dotenv
import os
import modal
from loguru import logger
import subprocess

@tool
def run_lammps(input: str, output_files: list[str] = [], save_path: str = None) -> None:
    """Run a LAMMPS simulation. The output is a dictionary where keys are file names, and the value is the content for that file. 
       For example in {"input.in" : ...., "log.lammps" : ..., "structure.xyz": ...} input.in is the input file for lammps, log.lammps is the log file of the simulation, structure.xyz is the xyz file saved .etc.

    Args:
        input: Input file contents for the LAMMPS simulation.
        output_files: List of expected output file names generated by the simulation.
        save_path: Directory path where output files should be saved. If None, files are not saved.
    """
    try:
        run_lammps_sim = modal.Function.lookup("simagent", "run_lammps")
        return run_lammps_sim.remote(input, output_files, save_path)
        # output_dict = run_lammps_sim.remote(input, output_files)
        # # Save files to the specified path if provided
        # if save_path:
        #     os.makedirs(save_path, exist_ok=True)
        #     for file_name, content in output_dict.items():
        #         file_path = os.path.join(save_path, file_name)
        #         with open(file_path, "w") as file:
        #             file.write(content)
    except ValueError as e:
        # Raise a ValueError with more context about the failure
        raise ValueError(f"The LAMMPS simulation failed with a ValueError: {str(e)}")
    except Exception as e:
        # Handle unexpected errors
        raise Exception(f"An unexpected error occurred while running the LAMMPS simulation: {str(e)}")



@tool
def run_bash_command(command: str, args: list[str] = []) -> str:
    """Execute a bash command with optional arguments.

    Args:
        command: The bash command to execute (e.g., 'mkdir', 'ls').
        args: A list of arguments for the bash command.
    """
    run_bash_command_modal = modal.Function.lookup("simagent", "run_bash_command")
    try:
        output = run_bash_command_modal.remote(command, args)
        return output
    except ValueError as ve:
        raise ValueError(f"Command Failed: {str(ve)}")
    except Exception as e:
        raise Exception(f"An unexpected error occured while running the command: {str(e)}")

def create_tools() -> Dict[str, Tool]:
    """Create all available tools"""
    return {
        "run_lammps": run_lammps,
        "run_bash_command": run_bash_command,
    }
    
