"""
Code2Latex - Automatic LaTeX documentation generation from Corral task environments.

This module provides utilities for generating formatted LaTeX files (with colorboxes)
containing task descriptions, tools, and scoring information. All data is kept in memory
and lost at the end of the run.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any, ClassVar

from loguru import logger

if TYPE_CHECKING:
    from collections.abc import Callable


@dataclass
class CacheMetadata:
    """Metadata for file naming."""

    env_name: str
    level: str | int


class Code2Latex:
    """
    Utility class for generating LaTeX documentation from task environments.

    This class provides methods to generate formatted LaTeX files with colorboxes
    containing task descriptions, available tools, and scoring information.
    """

    # LaTeX color scheme
    MAIN_TASK_COLORS: ClassVar[dict[str, str]] = {
        "background": "blue!5",
        "frame": "blue!75!black",
    }

    @classmethod
    def colorbox(
        cls,
        name: str,
        description: str,
        tools: list[str],
        scoring_fn: Callable,
        metadata: CacheMetadata,
        output_dir: str,
    ) -> str:
        """
        Generate LaTeX colorbox documentation for a task.

        Always generates and writes the .tex file immediately.

        Args:
            name: Task name
            description: Task description
            tools: List of tool names
            scoring_fn: Scoring function
            metadata: Metadata for file naming
            output_dir: Directory for .tex output

        Returns:
            Path to generated .tex file
        """
        # Build task data
        task_data = {
            "name": name,
            "description": description,
            "tools": tools,
            "scoring_function": scoring_fn.__name__
            if hasattr(scoring_fn, "__name__")
            else str(scoring_fn),
        }

        # Generate output file immediately
        output_path = (
            Path(output_dir) / f"{metadata.env_name}_level_{metadata.level}.tex"
        )
        output_path.parent.mkdir(parents=True, exist_ok=True)

        generated_path = cls._render_latex(task_data, output_path)
        logger.info(f"Generated LaTeX file: {generated_path}")

        return generated_path

    @classmethod
    def _render_latex(cls, task_data: dict[str, Any], output_path: Path) -> str:
        """Render the LaTeX file from task data. Appends if file already exists."""
        file_exists = output_path.exists()
        latex_content = cls._generate_latex_content(task_data, append=file_exists)

        mode = "a" if file_exists else "w"
        with output_path.open(mode, encoding="utf-8") as f:
            f.write(latex_content)

        return str(output_path)

    @classmethod
    def _generate_latex_content(
        cls, task_data: dict[str, Any], append: bool = False
    ) -> str:
        """Generate complete LaTeX content from task data.

        Args:
            task_data: Dictionary containing task information
            append: If True, skip preamble comments (for appending to existing file)
        """
        lines = []

        if not append:
            # Add LaTeX preamble comment only for new files
            lines.append("% Auto-generated by Code2Latex")
            lines.append("% Requires: tcolorbox, listings packages")
            lines.append("")
        else:
            # Add separator for appended tasks
            lines.append("")
            lines.append("% --- Additional task ---")
            lines.append("")

        # Generate task colorbox
        lines.append(cls._generate_task_colorbox(task_data))

        return "\n".join(lines)

    @classmethod
    def _generate_task_colorbox(
        cls,
        task: dict[str, Any],
    ) -> str:
        """Generate a task colorbox."""
        lines = []

        # Use main task colors
        colors = cls.MAIN_TASK_COLORS

        # Build title
        name = task.get("name", "Untitled Task")
        title = cls._escape_latex(name)

        # Start colorbox
        lines.append(rf"\begin{{tcolorbox}}[title={title}, breakable, enhanced,")
        lines.append(
            rf"                  colback={colors['background']}, colframe={colors['frame']}]"
        )
        lines.append("")

        # Add description
        description = task.get("description", "")
        if description:
            lines.append(cls._escape_latex(description))
            lines.append("")

        # Add tools
        tools = task.get("tools", [])
        if tools:
            lines.append(r"\medskip")
            tools_formatted = ", ".join(
                rf"\texttt{{{cls._escape_latex(t)}}}" for t in tools
            )
            lines.append(rf"\textbf{{Tools:}} {tools_formatted}")
            lines.append("")

        # Add scoring function
        scoring_fn = task.get("scoring_function", "")
        if scoring_fn:
            lines.append(r"\medskip")
            lines.append(
                rf"\textbf{{Scoring Function:}} \texttt{{{cls._escape_latex(scoring_fn)}}}"
            )
            lines.append("")

        # Close box
        lines.append(r"\end{tcolorbox}")

        return "\n".join(lines)

    @classmethod
    def _escape_latex(cls, text: str) -> str:
        """Escape special LaTeX characters in text."""
        if not text:
            return text

        # Characters that need escaping in LaTeX
        replacements = [
            ("\\", r"\textbackslash{}"),
            ("&", r"\&"),
            ("%", r"\%"),
            ("$", r"\$"),
            ("#", r"\#"),
            ("_", r"\_"),
            ("{", r"\{"),
            ("}", r"\}"),
            ("~", r"\textasciitilde{}"),
            ("^", r"\textasciicircum{}"),
        ]

        result = text
        for char, replacement in replacements:
            # Don't double-escape backslashes
            if char == "\\":
                # Only escape lone backslashes, not already escaped ones
                result = result.replace(char, replacement)
            else:
                result = result.replace(char, replacement)

        return result

    @classmethod
    def longtable(
        cls,
        tools: list[dict[str, Any]],
        metadata: CacheMetadata,
        output_dir: str,
    ) -> str:
        """
        Generate LaTeX longtable documentation for tools.

        Args:
            tools: List of tool dictionaries with keys:
                - name: Tool name
                - description: Tool description
                - arguments: List of argument dicts with name, type, description, required, default, choices
            metadata: Metadata for cache matching
            output_dir: Directory for .tex output

        Returns:
            Path to generated .tex file
        """
        # Create data entry with tools
        data = cls._create_tools_entry(metadata, tools)

        # Generate output file immediately
        output_path = (
            Path(output_dir) / f"{metadata.env_name}_level_{metadata.level}_tools.tex"
        )
        output_path.parent.mkdir(parents=True, exist_ok=True)

        generated_path = cls._render_longtable_latex(data, output_path)
        logger.info(f"Generated tools LaTeX file: {generated_path}")

        return generated_path

    @classmethod
    def _create_tools_entry(
        cls, metadata: CacheMetadata, tools: list[dict[str, Any]]
    ) -> dict[str, Any]:
        """Create a data entry for tools."""
        return {
            "metadata": asdict(metadata),
            "tools": {tool["name"]: tool for tool in tools},
        }

    @classmethod
    def _render_longtable_latex(
        cls, tools_data: dict[str, Any], output_path: Path
    ) -> str:
        """Render the LaTeX longtable file from tools data. Appends if file already exists."""
        file_exists = output_path.exists()
        latex_content = cls._generate_longtable_content(tools_data, append=file_exists)

        mode = "a" if file_exists else "w"
        with output_path.open(mode, encoding="utf-8") as f:
            f.write(latex_content)

        return str(output_path)

    @classmethod
    def _generate_longtable_content(
        cls, tools_data: dict[str, Any], append: bool = False
    ) -> str:
        """Generate complete LaTeX longtable content from tools data.

        Args:
            tools_data: Dictionary containing tools information
            append: If True, skip preamble comments (for appending to existing file)
        """
        lines = []

        if not append:
            # Add LaTeX preamble comment only for new files
            lines.append("% Auto-generated by Code2Latex")
            lines.append("% Requires: longtable, booktabs packages")
            lines.append("")
        else:
            # Add separator for appended tools
            lines.append("")
            lines.append("% --- Additional tools ---")
            lines.append("")

        tools = tools_data.get("tools", {})
        metadata = tools_data.get("metadata", {})

        if not tools:
            lines.append("% No tools found")
            return "\n".join(lines)

        # Sort tools by name for consistent ordering
        sorted_tools = sorted(tools.values(), key=lambda x: x.get("name", ""))

        # Begin longtable - single column for description-style layout
        lines.append(r"\begin{longtable}{p{\textwidth}}")
        lines.append(
            r"\caption{Tools for "
            + cls._escape_latex(metadata.get("env_name", "Unknown"))
            + r" (Level "
            + cls._escape_latex(str(metadata.get("level", "")))
            + r")} \\"
        )
        lines.append(r"\endfirsthead")
        lines.append("")
        lines.append(
            r"\multicolumn{1}{c}{\tablename\ \thetable{} -- continued from previous page} \\"
        )
        lines.append(r"\endhead")
        lines.append("")
        lines.append(r"\multicolumn{1}{r}{Continued on next page} \\")
        lines.append(r"\endfoot")
        lines.append("")
        lines.append(r"\endlastfoot")
        lines.append("")

        # Add each tool
        for i, tool in enumerate(sorted_tools):
            if i > 0:
                lines.append(r"\midrule")

            name = cls._escape_latex(tool.get("name", ""))
            description = cls._escape_latex(tool.get("description", ""))
            returns_info = cls._escape_latex(tool.get("returns", ""))

            # Tool name as header
            lines.append(rf"\textbf{{\texttt{{{name}}}}} \\")

            # Begin description environment
            lines.append(r"\begin{description}")

            # Tool description first
            lines.append(rf"    \item[\textbf{{Description:}}] {description}")

            # Format arguments
            arguments = tool.get("arguments", [])
            lines.append(r"    \item[\textbf{Arguments:}]")
            if arguments:
                lines.append(r"    \begin{description}")
                for arg in arguments:
                    arg_name = cls._escape_latex(arg.get("name", ""))
                    arg_type = cls._escape_latex(arg.get("type", ""))
                    arg_desc = cls._escape_latex(arg.get("description", ""))
                    lines.append(
                        rf"        \item \texttt{{{arg_name}}} ({arg_type}): {arg_desc}"
                    )
                lines.append(r"    \end{description}")
            else:
                lines.append(r"    None")

            # Returns section if available
            if returns_info:
                lines.append(rf"    \item[\textbf{{Returns:}}] {returns_info}")

            lines.append(r"\end{description} \\")

        lines.append(r"\end{longtable}")

        return "\n".join(lines)

    @classmethod
    def _format_tool_arguments(cls, arguments: list[dict[str, Any]]) -> str:
        """Format tool arguments for LaTeX table cell."""
        if not arguments:
            return "None"

        arg_lines = []
        for arg in arguments:
            name = cls._escape_latex(arg.get("name", ""))
            arg_type = cls._escape_latex(arg.get("type", ""))
            description = cls._escape_latex(arg.get("description", ""))
            required = arg.get("required", False)
            default = arg.get("default")
            choices = arg.get("choices")

            # Build argument string
            req_marker = "*" if required else ""
            arg_str = rf"\texttt{{{name}{req_marker}}} ({arg_type})"

            if description:
                arg_str += f": {description}"

            if choices:
                choices_str = ", ".join(cls._escape_latex(str(c)) for c in choices)
                arg_str += rf" [choices: {choices_str}]"
            elif default is not None:
                arg_str += rf" [default: {cls._escape_latex(str(default))}]"

            arg_lines.append(arg_str)

        # Join with newlines within the cell
        return r" \newline ".join(arg_lines)

    @classmethod
    def scoring_longtable(
        cls,
        scoring_functions: list[dict[str, Any]],
        metadata: CacheMetadata,
        output_dir: str,
    ) -> str:
        """
        Generate LaTeX longtable documentation for scoring functions.

        Unlike tools longtable, this collects ALL scoring functions from the task group
        at once, so we only write the file once and skip if it already exists.

        Args:
            scoring_functions: List of scoring function dictionaries with keys:
                - name: Function name
                - description: Function description (from docstring)
                - arguments: List of argument dicts with name, type, description, required, default
                - returns: Return value description
            metadata: Metadata for file naming
            output_dir: Directory for .tex output

        Returns:
            Path to generated .tex file
        """
        # Generate output file path
        output_path = (
            Path(output_dir) / f"{metadata.env_name}_level_{metadata.level}_scoring.tex"
        )
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Skip if file already exists - we collect all scoring functions at once,
        # so no need to append (unlike tools which may differ per task)
        if output_path.exists():
            logger.debug(
                f"Scoring functions LaTeX file already exists, skipping: {output_path}"
            )
            return str(output_path)

        # Create data entry with scoring functions
        data = cls._create_scoring_entry(metadata, scoring_functions)

        generated_path = cls._render_scoring_longtable_latex(data, output_path)
        logger.info(f"Generated scoring functions LaTeX file: {generated_path}")

        return generated_path

    @classmethod
    def _create_scoring_entry(
        cls, metadata: CacheMetadata, scoring_functions: list[dict[str, Any]]
    ) -> dict[str, Any]:
        """Create a data entry for scoring functions."""
        return {
            "metadata": asdict(metadata),
            "scoring_functions": {fn["name"]: fn for fn in scoring_functions},
        }

    @classmethod
    def _render_scoring_longtable_latex(
        cls, scoring_data: dict[str, Any], output_path: Path
    ) -> str:
        """Render the LaTeX longtable file from scoring functions data. Appends if file already exists."""
        file_exists = output_path.exists()
        latex_content = cls._generate_scoring_longtable_content(
            scoring_data, append=file_exists
        )

        mode = "a" if file_exists else "w"
        with output_path.open(mode, encoding="utf-8") as f:
            f.write(latex_content)

        return str(output_path)

    @classmethod
    def _generate_scoring_longtable_content(
        cls, scoring_data: dict[str, Any], append: bool = False
    ) -> str:
        """Generate complete LaTeX longtable content from scoring functions data.

        Args:
            scoring_data: Dictionary containing scoring functions information
            append: If True, skip preamble comments (for appending to existing file)
        """
        lines = []

        if not append:
            # Add LaTeX preamble comment only for new files
            lines.append("% Auto-generated by Code2Latex")
            lines.append("% Requires: longtable, booktabs packages")
            lines.append("")
        else:
            # Add separator for appended scoring functions
            lines.append("")
            lines.append("% --- Additional scoring functions ---")
            lines.append("")

        scoring_functions = scoring_data.get("scoring_functions", {})
        metadata = scoring_data.get("metadata", {})

        if not scoring_functions:
            lines.append("% No scoring functions found")
            return "\n".join(lines)

        # Sort scoring functions by name for consistent ordering
        sorted_fns = sorted(scoring_functions.values(), key=lambda x: x.get("name", ""))

        # Begin longtable - single column for description-style layout
        lines.append(r"\begin{longtable}{p{\textwidth}}")
        lines.append(
            r"\caption{Scoring Functions for "
            + cls._escape_latex(metadata.get("env_name", "Unknown"))
            + r" (Level "
            + cls._escape_latex(str(metadata.get("level", "")))
            + r")} \\"
        )
        lines.append(r"\endfirsthead")
        lines.append("")
        lines.append(
            r"\multicolumn{1}{c}{\tablename\ \thetable{} -- continued from previous page} \\"
        )
        lines.append(r"\endhead")
        lines.append("")
        lines.append(r"\multicolumn{1}{r}{Continued on next page} \\")
        lines.append(r"\endfoot")
        lines.append("")
        lines.append(r"\endlastfoot")
        lines.append("")

        # Add each scoring function
        for i, fn in enumerate(sorted_fns):
            if i > 0:
                lines.append(r"\midrule")

            name = cls._escape_latex(fn.get("name", ""))
            description = cls._escape_latex(fn.get("description", ""))
            returns_info = cls._escape_latex(fn.get("returns", ""))

            # Scoring function name as header
            lines.append(rf"\textbf{{\texttt{{{name}}}}} \\")

            # Begin description environment
            lines.append(r"\begin{description}")

            # Function description first
            if description:
                lines.append(rf"    \item[\textbf{{Description:}}] {description}")

            # Format arguments
            arguments = fn.get("arguments", [])
            lines.append(r"    \item[\textbf{Arguments:}]")
            if arguments:
                lines.append(r"    \begin{description}")
                for arg in arguments:
                    arg_name = cls._escape_latex(arg.get("name", ""))
                    arg_type = cls._escape_latex(arg.get("type", ""))
                    arg_desc = cls._escape_latex(arg.get("description", ""))
                    required = arg.get("required", False)
                    default = arg.get("default")

                    # Build argument entry
                    req_marker = " (required)" if required else ""
                    type_str = f" ({arg_type})" if arg_type else ""
                    default_str = (
                        f" [default: {cls._escape_latex(str(default))}]"
                        if default is not None
                        else ""
                    )

                    arg_entry = (
                        rf"        \item \texttt{{{arg_name}}}{type_str}{req_marker}"
                    )
                    if arg_desc:
                        arg_entry += f": {arg_desc}"
                    if default_str:
                        arg_entry += default_str

                    lines.append(arg_entry)
                lines.append(r"    \end{description}")
            else:
                lines.append(r"    None")

            # Returns section if available
            if returns_info:
                lines.append(rf"    \item[\textbf{{Returns:}}] {returns_info}")

            lines.append(r"\end{description} \\")

        lines.append(r"\end{longtable}")

        return "\n".join(lines)
