[project]
name = "corral-afm"
version = "0.1.0"
description = "AFM environment for the corral agent benchmark framework."
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Chandan Gupta", email = "chandan18386@iiitd.ac.in" }]
keywords = ["agent", "LLM", "benchmark"]
requires-python = ">=3.11"
dependencies = [
    "corral",
    "modal==0.70",
    "rich>=13.9.4",
    "ase", 
    "pypdf",
    "NSFopen",
    "nanosurf",
    "scikit-image",
    "langchain",
    "langchain_chroma",
    "langchain_core",
    "pymoo",
    "langgraph",
    "langchain_openai"

]
[tool.uv.sources]
corral = { path = "../../"} #TODO: change to main branch when merged