[project]
name = "catalyst"
version = "0.1.0"
description = "Corral Environment with tasks related to creating adsorbed structures"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ase>=3.25.0",
    "corral",
    "fastapi>=0.115.6",
    "ipython>=9.0.1",
    "more-itertools>=10.7.0",
    "mp-api>=0.45.3",
    "pymatgen>=2025.1.9",
    "python-dotenv>=1.0.1",
    "scikit-learn>=1.6.1",
    "uvicorn>=0.34.0",
    "xgboost>=3.0.2",
]

[tool.uv.sources]
# Use path dependency for monorepo setup
corral = { path = "../..", editable = true }

[dependency-groups]
dev = [
    "hypothesis>=6.136.0",
    "pytest-cov>=6.2.1",
    "pytest>=8.4.1",
    "pytest-mock>=3.14.1",
]
