[project]
name = "chembench-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chem-bench",
    "corral",
    "python-dotenv>=1.0.1",
    "loguru",
    "uvicorn>=0.34.0",
]

[tool.uv.sources]
chem-bench = { git = "https://github.com/lamalab-org/chem-bench.git", rev = "topic_wise_bench" }
corral = { git = "https://github.com/lamalab-org/mat-agent-bench.git", rev = "main" }
