[project]
name = "SpectraEluHard"
version = "0.1.0"
description = "Open Ended Spectra Elucidation task"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "corral",
    "loguru",
    "rdkit",
    "modal",
    "chromadb",
    "more-itertools",
    "uvicorn>=0.34.0",
]

[tool.uv.sources]
corral = { git = "https://github.com/lamalab-org/mat-agent-bench.git", rev = "main" }
