import inspect
from collections.abc import Callable
from copy import deepcopy
from typing import TYPE_CHECKING, Any

from agents.tool import function_tool as openai_function_tool

from corral.backend.schema import ToolArgument

if TYPE_CHECKING:
    from corral.router.verbosity import ToolVerbosity


class Tool:
    """Base class for tools.

    Stores tool metadata as a JSON Schema (params_json_schema) internally.
    The `arguments` property derives `ToolArgument` objects from the schema
    for backwards compatibility with code that iterates over arguments.

    For class-based tools (direct subclasses), pass `arguments` to `__init__`
    and they will be converted to a JSON Schema automatically.
    For function-based tools created via the `@tool` decorator, the schema is
    generated by the OpenAI Agents SDK `function_tool` and stored directly.
    """

    def __init__(
        self,
        name: str,
        description: str,
        arguments: list[ToolArgument] | None = None,
        params_json_schema: dict[str, Any] | None = None,
        hidden_args: dict[str, Any] | None = None,
    ):
        self.name = name
        self.description = description
        self.hidden_args = hidden_args or {}

        # Prefer an explicit schema when one is provided; otherwise derive it from
        # the ToolArgument list used by class-based tools.
        if params_json_schema is not None:
            self._params_json_schema = params_json_schema
        elif arguments is not None:
            self._params_json_schema = self._arguments_to_schema(arguments)
        else:
            self._params_json_schema = {
                "type": "object",
                "properties": {},
                "required": [],
            }

    @staticmethod
    def _arguments_to_schema(arguments: list[ToolArgument]) -> dict[str, Any]:
        """Convert a list of ToolArgument into a JSON Schema dict."""
        properties: dict[str, Any] = {}
        required: list[str] = []
        for arg in arguments:
            prop: dict[str, Any] = {
                "type": arg.type,
                "description": arg.description,
            }
            if arg.choices is not None:
                prop["enum"] = arg.choices
            if arg.default is not None:
                prop["default"] = arg.default
            properties[arg.name] = prop
            if arg.required:
                required.append(arg.name)
        return {"type": "object", "properties": properties, "required": required}

    @property
    def params_json_schema(self) -> dict[str, Any]:
        return self._params_json_schema

    @property
    def arguments(self) -> list[ToolArgument]:
        """Derive ToolArgument list from the JSON Schema for backwards compatibility."""
        args: list[ToolArgument] = []
        properties = self._params_json_schema.get("properties", {})
        required_set = set(self._params_json_schema.get("required", []))
        for param_name, prop in properties.items():
            raw_type = prop.get("type", "any")
            has_default = "default" in prop
            args.append(
                ToolArgument(
                    name=param_name,
                    type=raw_type,
                    description=prop.get("description", ""),
                    required=(param_name in required_set) and not has_default,
                    default=prop.get("default"),
                    choices=prop.get("enum"),
                )
            )
        return args

    def validate_arguments(
        self, provided_args: dict[str, Any]
    ) -> tuple[bool, str | None]:
        """Validate that all required arguments are provided with correct types."""
        for arg in self.arguments:
            if arg.required and arg.name not in provided_args:
                return False, f"Missing required argument: {arg.name}"

            if arg.name in provided_args:
                value = provided_args[arg.name]

                if arg.choices is not None and value not in arg.choices:
                    return (
                        False,
                        f"Invalid value for {arg.name}. Must be one of: {arg.choices}",
                    )

                try:
                    if arg.type == "integer":
                        int(value)
                    elif arg.type == "number":
                        float(value)
                    elif arg.type == "boolean":
                        isinstance(value, bool)
                except ValueError:
                    return (
                        False,
                        f"Invalid type for argument {arg.name}. Expected {arg.type}",
                    )

        return True, None

    def execute(self, **kwargs) -> str:
        """Execute the tool functionality."""
        raise NotImplementedError

    @classmethod
    def from_mcp(cls, mcp_tool_definition: dict[str, Any]) -> "Tool":
        """Create a Tool instance from an MCP tool definition (not implemented)."""
        raise NotImplementedError(
            "Converting from MCP to Corral Tool is not currently supported. "
        )

    def to_mcp(self, verbosity: "ToolVerbosity | None" = None) -> dict[str, Any]:
        """Convert this Tool to MCP-compatible dict format."""
        from corral.router.verbosity import ToolVerbosity, VerbosityConfig

        if verbosity is None:
            verbosity = ToolVerbosity.FULL

        filtered_description = VerbosityConfig.filter_tool_description(
            self.description, verbosity
        )

        schema = deepcopy(self._params_json_schema)
        schema.pop("additionalProperties", None)
        schema.pop("title", None)

        # Remove parameters with defaults from required — they are optional.
        properties = schema.get("properties", {})
        schema["required"] = [
            r
            for r in schema.get("required", [])
            if "default" not in properties.get(r, {})
        ]

        return {
            "name": self.name,
            "description": filtered_description,
            "inputSchema": schema,
        }

    def get_openai_tool_format(self) -> dict[str, Any]:
        """Return the tool definition in OpenAI function-calling format.

        Returns a dict like::

            {
                "type": "function",
                "function": {
                    "name": "...",
                    "description": "...",
                    "parameters": { <JSON Schema> }
                }
            }
        """
        schema = deepcopy(self._params_json_schema)
        schema.pop("additionalProperties", None)
        schema.pop("title", None)
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": schema,
            },
        }

    def get_usage_guide(self) -> str:
        """Generate a human-readable usage guide for the tool."""
        args_desc = []
        for arg in self.arguments:
            required = (
                "required" if arg.required else f"optional, default: {arg.default}"
            )
            args_desc.append(
                f"- {arg.name} ({arg.type}, {required}): {arg.description}"
            )

        return f"""Tool: {self.name}
Description: {self.description}
Arguments:
{chr(10).join(args_desc)}
"""


def _extract_field_defaults(func: Callable) -> dict[str, Any]:
    """Extract actual default values from parameters that use pydantic.Field.

    When a function parameter has `Field(default=X, ...)` as its default, Python
    sees the default as a `FieldInfo` object.  This helper returns a mapping of
    parameter name → real default value for those parameters so that `execute()`
    can inject them when the caller omits them.
    """
    from pydantic.fields import FieldInfo

    defaults: dict[str, Any] = {}
    sig = inspect.signature(func)
    for param_name, param in sig.parameters.items():
        if isinstance(param.default, FieldInfo) and param.default.default is not None:
            # Skip required fields, which use PydanticUndefined instead of a real default.
            from pydantic_core import PydanticUndefined

            if param.default.default is not PydanticUndefined:
                defaults[param_name] = param.default.default
    return defaults


def tool(
    func: Callable | None = None, *, hidden_args: list[str] | None = None
) -> Tool | Callable[[Callable], Tool]:
    """Decorator to convert a function into a Tool.

    Uses the OpenAI Agents SDK `function_tool` under the hood to generate
    the JSON Schema from the function signature (including `pydantic.Field`
    annotations for descriptions, defaults, and constraints).

    The function must have:
    1. A docstring (used as the tool description).
    2. Type hints for all parameters and the return type.

    Parameter metadata (description, choices, defaults) should be declared
    via `pydantic.Field` default values::

        from pydantic import Field
        from typing import Literal

        @tool
        def calculator(
            operation: Literal["add", "subtract"] = Field(description="Math op"),
            x: float = Field(description="First number"),
            y: float = Field(description="Second number"),
        ) -> str:
            \"\"\"Perform basic math operations.\"\"\"
            ...

    Args:
        func: The function to convert into a tool.
        hidden_args: List of parameter names that should be excluded from
            the schema exposed to the agent. Their default values are
            recorded so the environment can inject them at call time.

    Returns:
        A `Tool` instance wrapping the function.
    """

    def decorator(func: Callable) -> Tool:
        if not func.__doc__:
            raise ValueError(
                f"Function {func.__name__} must have a docstring describing its purpose."
            )

        # Use the Agents SDK schema so decorator-based tools stay aligned with runtime behavior.
        ft = openai_function_tool(func)

        # Copy the schema before removing hidden arguments or other internal details.
        schema = deepcopy(ft.params_json_schema)

        # Capture hidden argument defaults so the environment can inject them at execution time.
        hidden_args_dict: dict[str, Any] = {}
        if hidden_args:
            sig = inspect.signature(func)
            for arg_name in hidden_args:
                if arg_name not in sig.parameters:
                    raise ValueError(
                        f"Hidden arg '{arg_name}' does not exist in function signature."
                    )
                param = sig.parameters[arg_name]
                hidden_args_dict[arg_name] = (
                    param.default
                    if param.default is not inspect.Parameter.empty
                    else None
                )
            # Exclude hidden arguments from the schema exposed to the agent.
            hidden_set = set(hidden_args)
            if "properties" in schema:
                for ha in hidden_set:
                    schema["properties"].pop(ha, None)
            if "required" in schema:
                schema["required"] = [
                    r for r in schema["required"] if r not in hidden_set
                ]

        class _FunctionTool(Tool):
            def __init__(self):
                self._func = func
                self._openai_function_tool = ft
                # Resolve FieldInfo defaults once so execute() can apply them consistently.
                self._field_defaults = _extract_field_defaults(func)
                super().__init__(
                    name=ft.name,
                    description=ft.description,
                    params_json_schema=schema,
                    hidden_args=hidden_args_dict if hidden_args_dict else None,
                )

            def execute(self, **kwargs):
                # Apply FieldInfo defaults when the caller omits those parameters.
                for param_name, default_val in self._field_defaults.items():
                    if param_name not in kwargs:
                        kwargs[param_name] = default_val
                return str(func(**kwargs))

        return _FunctionTool()

    # Support both @tool and @tool(hidden_args=[...]) invocation styles.
    if func is None:
        return decorator
    else:
        return decorator(func)
