from __future__ import annotations

from modal import Image

_lammps_image = (
    Image.debian_slim(python_version="3.12")
    .apt_install(
        "git",
        "cmake",
        "wget",
        "build-essential",
        "liblapack-dev",
        "libfftw3-dev",
        "libopenmpi-dev",
        "openmpi-bin"
    )
    .pip_install("loguru")
)
with _lammps_image.imports():
    import os
    import subprocess

    from loguru import logger


def _install_lammps():

    try:
        logger.debug("Cloning LAMMPS repository...")    
        subprocess.run(["git", "clone", "https://github.com/lammps/lammps.git"], check=True)

        logger.debug("Making lammps/build directory")
        os.makedirs("lammps/build", exist_ok=True)

        logger.debug("Changing to lammps/build")
        os.chdir("lammps/build")
        
        logger.debug("Running CMAKE for MANY BODY PACKAGE")
        subprocess.check_call("cmake ../cmake -D PKG_MANYBODY=on -D PKG_ATC=yes", shell=True)
    
        logger.debug("CMAKE build...")
        subprocess.check_call("cmake --build .", shell=True)

        logger.debug("MAKE for installing...")
        subprocess.check_call("make install", shell=True)
    
        logger.debug("Adding LAMMPS to PATH...")
        home = os.path.expanduser("~")
        bashrc_path = os.path.join(home, ".bashrc")
        with open(bashrc_path, "a") as f:
            f.write('\nexport PATH="/root/lammps/build:$PATH"\n')

        logger.debug("Updating shell environment...")
        subprocess.run(f"bash -c 'source {bashrc_path}'", shell=True, check=True)

        logger.debug("LAMMPS installation completed successfully")
        return "LAMMPS installed successfully"
    
    except subprocess.CalledProcessError as e:
        logger.error(f"Installation failed at step: {e.cmd}")
        raise Exception(f"Installation failed at step: {e.cmd}")

lammps_image = _lammps_image.run_function(_install_lammps)

def _run_lammps(input: str, output_files: list[str] = []) -> dict:
    """
    Runs a LAMMPS simulation using the specified input file.

    Args:
        input (str): The content of the input script to run the simulation.
        output_files (list[str]): List of expected output file names generated by LAMMPS.
    
    Returns:
        dict: A dictionary containing the log file content and other outputs.
    """
    input_file = "input.in"
    log_file = "log.lammps"
    lmp_command = "/root/lammps/build/lmp"
    
    try:
        # Write input script to a file
        with open(input_file, "w") as f:
            f.write(input)
        logger.debug(f"Input script written to file: {input_file}")
    except OSError as e:
        logger.error(f"Failed to write input file: {e}")
        raise e

    try:
        # Construct the LAMMPS command
        command = [lmp_command, "-in", input_file]

        logger.debug(f"Executing LAMMPS command: {' '.join(command)}")
        subprocess.run(command, shell=False, check=True, capture_output=True, text=True)

        # Collect results
        results = {"input.in" : input}

        # Read log file content
        if os.path.exists(log_file):
            with open(log_file, "r") as log:
                results["log"] = log.read()
                logger.debug(f"Read log file ({log_file}) content: {len(results['log'])} characters")
        else:
            logger.warning(f"Log file ({log_file}) not found.")

        # Read additional output files
        for output_file in output_files:
            if os.path.exists(output_file):
                with open(output_file, "r") as out:
                    results[output_file] = out.read()
                    logger.debug(f"Read output file ({output_file}) content: {len(results[output_file])} characters")
            else:
                logger.warning(f"Output file ({output_file}) not found.")

        # Clean up: Remove the input file and output files after processing
        try:
            os.remove(input_file)
            logger.debug(f"Deleted input file: {input_file}")
        except OSError as e:
            logger.warning(f"Failed to delete input file: {e}")

        if os.path.exists(log_file):
            try:
                os.remove(log_file)
                logger.debug(f"Deleted log file: {log_file}")
            except OSError as e:
                logger.warning(f"Failed to delete log file: {e}")

        for output_file in output_files:
            if os.path.exists(output_file):
                try:
                    os.remove(output_file)
                    logger.debug(f"Deleted output file: {output_file}")
                except OSError as e:
                    logger.warning(f"Failed to delete output file: {output_file} - {e}")

        return results

    except subprocess.CalledProcessError as e:
        logger.error(f"LAMMPS execution failed: {e.cmd}")
        raise Exception(f"LAMMPS execution failed: {e.cmd}\n{e.stderr}")

    except Exception as e:
        logger.error(f"An unexpected error occurred: {str(e)}")
        raise e
