from __future__ import annotations

from modal import Image

_lammps_image = (
    Image.debian_slim(python_version="3.12")
    .apt_install(
        "git",
        "cmake",
        "wget",
        "build-essential",
        "liblapack-dev",
        "libfftw3-dev",
        "libopenmpi-dev",
        "openmpi-bin"
    )
    .pip_install("loguru")
)
with _lammps_image.imports():
    import os
    import subprocess

    from loguru import logger


def _install_lammps():

    try:
        logger.debug("Cloning LAMMPS repository...")    
        subprocess.run(["git", "clone", "https://github.com/lammps/lammps.git"], check=True)

        logger.debug("Making lammps/build directory")
        os.makedirs("lammps/build", exist_ok=True)

        logger.debug("Changing to lammps/build")
        os.chdir("lammps/build")
        
        logger.debug("Running CMAKE for MANY BODY PACKAGE")
        subprocess.check_call("cmake ../cmake -D PKG_MANYBODY=on -D PKG_ATC=yes", shell=True)
    
        logger.debug("CMAKE build...")
        subprocess.check_call("cmake --build .", shell=True)

        logger.debug("MAKE for installing...")
        subprocess.check_call("make install", shell=True)
    
        logger.debug("Adding LAMMPS to PATH...")
        home = os.path.expanduser("~")
        bashrc_path = os.path.join(home, ".bashrc")
        with open(bashrc_path, "a") as f:
            f.write('\nexport PATH="/root/lammps/build:$PATH"\n')

        logger.debug("Updating shell environment...")
        subprocess.run(f"bash -c 'source {bashrc_path}'", shell=True, check=True)

        logger.debug("LAMMPS installation completed successfully")
        return "LAMMPS installed successfully"
    
    except subprocess.CalledProcessError as e:
        logger.error(f"Installation failed at step: {e.cmd}")
        raise Exception(f"Installation failed at step: {e.cmd}")

lammps_image = _lammps_image.run_function(_install_lammps)

def _run_lammps(input: str, output_files: list[str] = [], directory_path: str = None) -> dict:
    """
    Runs a LAMMPS simulation using the specified input file.

    Args:
        input (str): The content of the input script to run the simulation.
        output_files (list[str]): List of expected output file names generated by LAMMPS.

    Returns:
        dict: A dictionary containing the log file content and other outputs.

    Raises:
        ValueError: If the LAMMPS simulation fails with the captured error message.
    """
    import os
    import subprocess
    import logging
    import gc
    import io

    logger = logging.getLogger(__name__)

    input_file = "input.in"
    log_file = "log.lammps"
    lmp_command = "/root/lammps/build/lmp"
    results = {}

    original_cwd = os.getcwd()
    if directory_path:
        os.chdir(directory_path)

    try:
        print("Current directory:", os.getcwd())

        # Write input script
        with open(input_file, "w") as f:
            f.write(input)
        logger.debug(f"Input script written: {input_file}")

        # Run LAMMPS
        command = [lmp_command, "-in", input_file]
        logger.debug(f"Executing: {' '.join(command)}")

        subprocess.run(command, shell=False, check=True, capture_output=True, text=True)

        # Read log file safely
        if os.path.exists(log_file):
            with open(log_file, "r") as log:
                results[log_file] = log.read()
        else:
            logger.warning(f"{log_file} not found.")

        # Read other output files safely
        for output_file in output_files:
            if os.path.exists(output_file):
                with open(output_file, "r") as out:
                    results[output_file] = out.read()
            else:
                logger.warning(f"{output_file} not found.")

        results["input.in"] = input  # Store input script
        return results

    finally:
        os.chdir(original_cwd)  # Restore original directory

    # finally:
    #     # Ensure all temporary files are deleted
    #     for file in [input_file, log_file] + output_files:
    #         if os.path.exists(file):
    #             try:
    #                 os.remove(file)
    #                 logger.debug(f"Deleted file: {file}")
    #             except OSError as e:
    #                 logger.warning(f"Failed to delete file {file}: {e}")




