import inspect
from collections.abc import Callable
from copy import deepcopy
from dataclasses import dataclass
from enum import Enum
from typing import Any, Literal

from agents.tool import function_tool as openai_function_tool
from pydantic.fields import FieldInfo
from pydantic_core import PydanticUndefined

from corral.core.tool_description import (
    default_argument_description,
    default_tool_description,
)

ToolTransport = Literal["python", "mcp"]


@dataclass(frozen=True, slots=True)
class ToolResponse:
    success: bool
    result: str | None
    error: str | None


@dataclass(frozen=True, slots=True)
class ToolConnection:
    """Runtime-provided access details for one agent invocation.

    Connections are ephemeral and must not be restored from execution state.
    Python callers execute actions directly; MCP callers receive a local URL.
    """

    transport: ToolTransport = "python"
    url: str | None = None

    @property
    def mcp_url(self) -> str:
        if self.transport != "mcp" or self.url is None:
            raise RuntimeError(
                "MCP tools have not been provisioned for this agent invocation; "
                "run the agent through TaskRuntime or run_agent_session"
            )
        return self.url


class ToolCallStatus(Enum):
    SUCCESS = "success"
    INVALID_TOOL = "invalid_tool"
    INVALID_ARGS = "invalid_args"
    EXECUTION_ERROR = "execution_error"


@dataclass
class ToolArgument:
    """Specification for a tool argument."""

    name: str
    type: str
    description: str
    required: bool = True
    default: Any = None
    choices: list[Any] | None = None


class ToolConcurrency(str, Enum):
    """How a tool may be scheduled relative to other tool calls in one runtime.

    Concurrent tool calls can arrive on a single task execution when an agent
    adapter issues them in parallel. This mode tells the
    :class:`~corral.core.environment.Environment` how safe a tool is to overlap
    with other executions of the same bound runtime:

    * `SERIAL` (the default) — take the runtime's state lock for the whole
      call, so the tool runs alone. Every existing tool defaults here, so nothing
      overlaps until a tool explicitly opts in.
    * `READ_ONLY` — the tool does not mutate runtime state *at all*, so it may
      run alongside any other non-serial call with no execution lock; only the
      recording of its result is serialised.
    * `CONCURRENT` — the tool may mutate the single resource named by its
      `concurrency_key` (a *writer* on that resource). Calls sharing a key are
      serialised against each other, against `CONCURRENT_READ` calls on the
      same key, and against background jobs on the same key; different keys run
      in parallel.
    * `CONCURRENT_READ` — the read side of the same `concurrency_key`
      resource: the tool only *reads* that resource, so same-key readers overlap
      each other (unlike `CONCURRENT`, which is exclusive) while still being
      mutually exclusive with same-key `CONCURRENT` writers and background
      jobs. This is the read/write split within one resource — a
      readers-writer lock keyed by `concurrency_key` — as opposed to
      `READ_ONLY`, which touches no shared resource and takes no lock at all.

    Subclassing `str` keeps the value JSON-serialisable and comparable to the
    plain strings accepted by the `@tool` decorator.
    """

    SERIAL = "serial"
    READ_ONLY = "read_only"
    CONCURRENT = "concurrent"
    CONCURRENT_READ = "concurrent_read"


class Tool:
    """Base class for tools.

    Stores tool metadata as a JSON Schema (params_json_schema) internally.
    The `arguments` property derives structured `ToolArgument` views from that
    canonical schema for validation and human-readable guides.

    Function-based tools created via the `@tool` decorator receive a schema
    generated by the OpenAI Agents SDK `function_tool`.
    """

    def __init__(
        self,
        name: str,
        description: str,
        params_json_schema: dict[str, Any] | None = None,
        hidden_args: dict[str, Any] | None = None,
        background_capable: bool = False,
        executor: str | None = None,
        concurrency_key: str | None = None,
        concurrency: "ToolConcurrency | str" = ToolConcurrency.SERIAL,
        trusted: bool = False,
        workspace_args: tuple[str, ...] = (),
    ):
        self.name = name
        self.description = description
        self.hidden_args = hidden_args or {}
        # Docker tools are restricted by default. Only explicitly trusted task
        # logic may receive private inputs and run in the controller; it must
        # never evaluate model-supplied code or load workspace executables.
        self.trusted = trusted
        self.workspace_args = tuple(workspace_args)
        if not set(self.workspace_args) <= self.hidden_args.keys():
            raise ValueError("workspace_args must name hidden arguments")
        # Background-execution metadata (PR 4). A tool marked
        # `background_capable` gets a generated `start_<tool>` variant that runs
        # it as a background job so the agent is not blocked while it runs.
        # `executor` names the preferred :class:`JobExecutor` backend (currently
        # advisory; the default thread executor is always used). `concurrency_key`
        # serialises background jobs that contend for the same resource.
        self.background_capable = background_capable
        self.executor = executor
        self.concurrency_key = concurrency_key
        # Concurrent-tool-call safety (Section 9). Defaults to SERIAL so an
        # existing tool never overlaps another call unless it opts in; the
        # environment reads this to pick the lock it holds during execution.
        self.concurrency = ToolConcurrency(concurrency)
        self._params_json_schema = params_json_schema or {
            "type": "object",
            "properties": {},
            "required": [],
        }

    @property
    def params_json_schema(self) -> dict[str, Any]:
        return self._params_json_schema

    @property
    def arguments(self) -> list[ToolArgument]:
        """Derive structured arguments from the canonical JSON Schema."""
        args: list[ToolArgument] = []
        properties = self._params_json_schema.get("properties", {})
        required_set = set(self._params_json_schema.get("required", []))
        for param_name, prop in properties.items():
            raw_type = prop.get("type", "any")
            has_default = "default" in prop
            is_nullable = any(
                variant.get("type") == "null" for variant in prop.get("anyOf", [])
            )
            args.append(
                ToolArgument(
                    name=param_name,
                    type=raw_type,
                    description=prop.get("description", ""),
                    required=(param_name in required_set)
                    and not has_default
                    and not is_nullable,
                    default=prop.get("default"),
                    choices=prop.get("enum"),
                )
            )
        return args

    def validate_arguments(
        self, provided_args: dict[str, Any]
    ) -> tuple[bool, str | None]:
        """Validate that all required arguments are provided with correct types."""
        for arg in self.arguments:
            if arg.required and arg.name not in provided_args:
                return False, f"Missing required argument: {arg.name}"

            if arg.name in provided_args:
                value = provided_args[arg.name]

                if arg.choices is not None and value not in arg.choices:
                    return (
                        False,
                        f"Invalid value for {arg.name}. Must be one of: {arg.choices}",
                    )

                try:
                    if arg.type == "integer":
                        int(value)
                    elif arg.type == "number":
                        float(value)
                except ValueError:
                    return (
                        False,
                        f"Invalid type for argument {arg.name}. Expected {arg.type}",
                    )

        return True, None

    def execute(self, **kwargs) -> Any:
        """Execute the tool functionality."""
        raise NotImplementedError

    def get_openai_tool_format(self) -> dict[str, Any]:
        """Return the fixed-default tool definition in provider format.

        Returns a dict like::

            {
                "type": "function",
                "function": {
                    "name": "...",
                    "description": "...",
                    "parameters": { <JSON Schema> }
                }
            }
        """
        schema = deepcopy(self._params_json_schema)
        schema.pop("additionalProperties", None)
        schema.pop("title", None)
        for prop in schema.get("properties", {}).values():
            description = prop.get("description")
            if isinstance(description, str):
                prop["description"] = default_argument_description(description)
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": default_tool_description(self.description),
                "parameters": schema,
            },
        }

    def get_usage_guide(self) -> str:
        """Generate a human-readable usage guide for the tool."""
        args_desc = []
        for arg in self.arguments:
            required = (
                "required" if arg.required else f"optional, default: {arg.default}"
            )
            args_desc.append(
                f"- {arg.name} ({arg.type}, {required}): "
                f"{default_argument_description(arg.description)}"
            )

        return f"""Tool: {self.name}
Description: {default_tool_description(self.description)}
Arguments:
{chr(10).join(args_desc)}
"""


def _extract_field_defaults(func: Callable) -> dict[str, Any]:
    """Extract actual default values from parameters that use pydantic.Field.

    When a function parameter has Field(default=X, ...) as its default, Python
    sees the default as a FieldInfo object. This helper returns a mapping of
    parameter name to real default value so that execute() can inject them
    when the caller omits them.

    Args:
        func: The function whose signature will be inspected.

    Returns:
        A dict mapping parameter names to their resolved default values.
    """
    defaults: dict[str, Any] = {}
    sig = inspect.signature(func)
    for param_name, param in sig.parameters.items():
        if (
            isinstance(param.default, FieldInfo)
            and param.default.default is not None
            and param.default.default is not PydanticUndefined
        ):
            defaults[param_name] = param.default.default
    return defaults


def tool(
    func: Callable | None = None,
    *,
    hidden_args: list[str] | None = None,
    background_capable: bool = False,
    executor: str | None = None,
    concurrency_key: str | None = None,
    concurrency: "ToolConcurrency | str" = ToolConcurrency.SERIAL,
    trusted: bool = False,
    workspace_args: tuple[str, ...] = (),
) -> Tool | Callable[[Callable], Tool]:
    """Decorator to convert a function into a Tool.

    Uses the OpenAI Agents SDK function_tool under the hood to generate
    the JSON Schema from the function signature (including pydantic.Field
    annotations for descriptions, defaults, and constraints).

    The function must have:
    1. A docstring (used as the tool description).
    2. Type hints for all parameters and the return type.

    Parameter metadata (description, choices, defaults) should be declared
    via pydantic.Field default values::

        from pydantic import Field
        from typing import Literal

        @tool
        def calculator(
            operation: Literal["add", "subtract"] = Field(description="Math op"),
            x: float = Field(description="First number"),
            y: float = Field(description="Second number"),
        ) -> str:
            \"\"\"Perform basic math operations.\"\"\"
            ...

    Args:
        func: The function to convert into a Tool.
        hidden_args: List of parameter names that should be excluded from
            the schema exposed to the agent. Their default values are
            recorded so the environment can inject them at call time.
        background_capable: Mark this as a long-running tool that should also be
            exposed as a generated `start_<tool>` variant, letting the agent run
            it as a background job and continue working while it runs (PR 4).
        executor: Preferred :class:`~corral.backend.executors.JobExecutor` backend for
            background runs (advisory for now; the thread executor is used).
        concurrency_key: Names the shared resource this tool contends for.
            Background jobs sharing this key are serialised so tools contending
            for the same resource never run at once. When
            `concurrency="concurrent"` it also serialises *foreground* (writer)
            calls of this tool against same-key calls and jobs; when
            `concurrency="concurrent_read"` the call takes the *read* side of
            the same key, so same-key readers overlap while writers stay
            exclusive (a readers-writer split within one resource).
        concurrency: How this tool may overlap other tool calls in one runtime
            (see :class:`ToolConcurrency`). Defaults to `SERIAL`.
        trusted: Run task logic with private inputs in the Docker controller.
            Never enable this for shell, Python, untrusted file-loading, or other tools
            that execute model-controlled code. Restricted execution is default.
        workspace_args: Hidden arguments that carry only the assigned workspace
            path. Docker workers receive a fresh binding from the controller,
            never the corresponding value from private environment state.

    Returns:
        A Tool instance wrapping the function.
    """

    def decorator(func: Callable) -> Tool:
        if not func.__doc__:
            raise ValueError(
                f"Function {func.__name__} must have a docstring describing its purpose."
            )

        ft = openai_function_tool(func)

        schema = deepcopy(ft.params_json_schema)

        hidden_args_dict: dict[str, Any] = {}
        if hidden_args:
            sig = inspect.signature(func)
            for arg_name in hidden_args:
                if arg_name not in sig.parameters:
                    raise ValueError(
                        f"Hidden arg '{arg_name}' does not exist in function signature."
                    )
                param = sig.parameters[arg_name]
                hidden_args_dict[arg_name] = (
                    param.default
                    if param.default is not inspect.Parameter.empty
                    else None
                )
            hidden_set = set(hidden_args)
            if "properties" in schema:
                for ha in hidden_set:
                    schema["properties"].pop(ha, None)
            if "required" in schema:
                schema["required"] = [
                    r for r in schema["required"] if r not in hidden_set
                ]

        class _FunctionTool(Tool):
            def __init__(self):
                self._func = func
                self._field_defaults = _extract_field_defaults(func)
                super().__init__(
                    name=ft.name,
                    description=ft.description,
                    params_json_schema=schema,
                    hidden_args=hidden_args_dict if hidden_args_dict else None,
                    background_capable=background_capable,
                    executor=executor,
                    concurrency_key=concurrency_key,
                    concurrency=concurrency,
                    trusted=trusted,
                    workspace_args=workspace_args,
                )

            def execute(self, **kwargs):
                for param_name, default_val in self._field_defaults.items():
                    if param_name not in kwargs:
                        kwargs[param_name] = default_val
                result = func(**kwargs)
                # Stateful tools return a structured observation and
                # complete environment replacement. Preserve that value for
                # the runtime; ordinary function tools keep their textual tool
                # result contract.
                from corral.core.transition import (  # - avoid import cycle
                    ToolExecutionResult,
                )

                return (
                    result if isinstance(result, ToolExecutionResult) else str(result)
                )

        return _FunctionTool()

    # Support both @tool and @tool(hidden_args=[...]) invocation styles.
    if func is None:
        return decorator
    else:
        return decorator(func)
