import importlib.resources
import traceback
from abc import ABC, abstractmethod
from functools import partial
from typing import Any, Self

import anyio
from litellm.exceptions import ContextWindowExceededError
from litellm.types.utils import Message
from loguru import logger
from promptstore import PromptStore

from corral.agents.hooks import AgentHooks, HookContext, HookPoint
from corral.agents.prompt_utils import ensure_jinja_compatible, get_prompt
from corral.agents.schema import SURRENDER_SENTINEL, AgentRunResult
from corral.agents.utils import (
    LiteLLMMessage,
    LLMResponse,
    count_tokens_and_add,
    llm_call,
    save_agent_messages,
)
from corral.router.routes import CorralRouter, as_sync_interface
from corral.types import BudgetExhaustedError


class BaseAgent(ABC):
    """
    Base Agent class that captures common functionality for different agent types.

    This abstract base class provides common initialization parameters and methods
    for agent implementations.

    ## Prompt System Overview

    ### Prompt Types:
    - **system_prompt**: Sets the agent's behavior and role (e.g., "You are a helpful AI assistant")
    - **user_prompt**: Contains the main task instructions with placeholders for dynamic content
    - **extractor_prompt**: Used to extract and clean final answers from agent responses.
      This prompt takes the raw agent output and extracts just the answer portion, removing
      explanatory text, formatting artifacts, or multiple choice options.
    - **surrender_prompt**: Instructions for how the agent can surrender from unsolvable tasks.
      This prompt is only included when enable_surrender=True in the run() method and will be added to the task prompt.


    Depending of the agent type, different user_prompt templates are required with specific
    placeholders and formatting instructions.

    Args:
        model (str): The model to use for running the agent. Defaults to "openai/gpt-4o".
        max_iterations (int, optional): The maximum number of iterations (number of LLM calls) to run. Defaults to 10.
        api_endpoint (str, optional): The API endpoint URL for the LLM provider
            (e.g., OpenAI, VLLM, or self-hosted models) to handle requests. Defaults to None meaning that it uses LiteLLM.
        system_prompt (str, optional): The system prompt to use. Must be an string.
            If None, uses default system prompt at "src/corral/agents/prompts/system_prompt/system_prompt/prompt.md".
        user_prompt (str, optional): The user prompt to use. Must be an string with the different variables required by each agent.
            If None, uses default prompt specific to each agent type.
        extractor_prompt (str, optional): The extractor prompt for cleaning final answers.
            If None, uses default extractor prompt at "src/corral/agents/prompts/extractor_prompt/extractor_prompt/prompt.md".
            Must be a string that supports the next variables:
                - `answer`: The raw answer generated by the agent
                - `message`: The full message context including task description and agent response
        surrender_prompt (str, optional): The surrender prompt with instructions for surrendering.
            This is, when the agent cannot solve a task, it can give up by following this instruction.
            Must be a string.
        temperature (float, optional): The temperature to use for sampling. Defaults to 0.7.
        **kwargs: Additional keyword arguments to pass to the LiteLLM API
    """

    def __init__(
        self,
        model: str = "openai/gpt-4o",
        max_iterations: int = 10,
        api_endpoint: str | None = None,
        system_prompt: str | None = None,
        user_prompt: str | None = None,
        extractor_prompt: str | None = None,
        surrender_prompt: str | None = None,
        temperature: float = 0.7,
        hooks: AgentHooks | None = None,
        **kwargs,
    ):
        """Initialize the base agent with common parameters"""
        self.model = model
        self.max_iterations = max_iterations
        self.api_endpoint = api_endpoint
        self.temperature = temperature
        self.messages: list = []
        # `token_usage` holds the *most recent* LLM call's usage. It doubles as
        # the current context size for the context-budget message and Terminus-2
        # compaction, so it must stay per-call and not accumulate.
        self.token_usage: dict = {}
        # `cumulative_token_usage` sums usage across every LLM call in the run,
        # so `get_total_token_usage` reflects the whole conversation rather than
        # only the last completion.
        self.cumulative_token_usage: dict = {}
        self.hooks = hooks or AgentHooks()
        self._current_iteration = 0  # Track current iteration for hooks
        self._initial_messages: list[LiteLLMMessage] | None = None

        with importlib.resources.path("corral.agents", "") as style_path:
            self.store = PromptStore(f"{style_path}/prompts")

        self.kwargs = kwargs

        # Default prompt IDs
        default_system_prompt_id = "system_prompt/system_prompt"
        default_extractor_prompt_id = "extractor_prompt/extractor_prompt"

        # Handle system prompt - convert to string immediately as it typically doesn't need variables
        if system_prompt is None:
            self.system_prompt = get_prompt(
                self.store, None, default_system_prompt_id
            ).fill({})
        else:
            system_prompt_obj = ensure_jinja_compatible(system_prompt)
            self.system_prompt = system_prompt_obj.fill({})

        # Handle user prompt (subclasses should set their default)
        try:
            self.user_prompt = self.store.get(user_prompt)
        except Exception:
            self.user_prompt = ensure_jinja_compatible(user_prompt)

        # Handle extractor prompt
        if extractor_prompt is None:
            self.extractor_prompt = get_prompt(
                self.store, extractor_prompt, default_extractor_prompt_id
            )
        else:
            self.extractor_prompt = ensure_jinja_compatible(extractor_prompt)

        if surrender_prompt is not None:
            self.surrender_prompt = ensure_jinja_compatible(surrender_prompt)
        else:
            self.surrender_prompt = None

    @classmethod
    def from_trace(
        cls,
        trace: list[LiteLLMMessage],
        **init_kwargs,
    ) -> Self:
        """Construct an agent pre-loaded with a previous conversation trace.

        This classmethod creates a new agent instance whose message history is
        initialised from `trace`.  When the agent's `run()` method is
        called it will use these messages instead of building a fresh prompt,
        allowing benchmarks to be replayed from saved traces.

        Args:
            trace: A list of `LiteLLMMessage` dicts representing the
                conversation history from a previous run.
            **init_kwargs: All remaining keyword arguments are forwarded to
                the class `__init__`.

        Returns:
            A new agent instance with `_initial_messages` set to the
            provided trace.
        """
        agent = cls(**init_kwargs)
        agent._initial_messages = list(trace)
        return agent

    def get_llm_response(
        self, tools: list[dict[str, Any]] | None = None, **call_kwargs: Any
    ) -> Any:
        """Get response from the LLM using LiteLLM

        Args:
            tools (dict[str, Any], optional): Optional tools/functions for function calling
            **call_kwargs: Per-call keyword arguments merged over (and taking
                precedence over) the agent-wide `self.kwargs` for this single
                request. Use this for options that must not leak into other LLM
                calls made by the agent (e.g. passing `response_format` for a
                structured-output turn without forcing the final-answer extractor
                to use the same schema).

        Returns:
            Any: The LLMResponse wrapper containing the message and metadata
        """
        self.messages = count_tokens_and_add(
            self.messages, self.model, self.token_usage.get("total_tokens", 0)
        )
        merged_kwargs = {**self.kwargs, **call_kwargs}
        try:
            response = llm_call(
                model=self.model,
                messages=self.messages,
                tools=tools,
                temperature=self.temperature,
                api_endpoint=self.api_endpoint,
                return_usage=True,
                **merged_kwargs,
            )

            # Track token usage from metadata. `token_usage` keeps the latest
            # call (current context size); `cumulative_token_usage` adds each
            # call on top of the older usage so the run total spans the whole
            # conversation, not just the last completion.
            if response.usage:
                self.token_usage = response.usage
                self._accumulate_token_usage(response.usage)

            return response

        except ContextWindowExceededError as e:
            logger.error(f"API error: {e}")

            for message in reversed(self.messages):
                if message["role"] != "assistant":
                    if "content" in message:
                        content = str(message["content"])
                        if len(content) > 100:
                            message["content"] = content[:100] + "..."
                else:
                    break

            error_message = f"{type(e).__name__}: {e!s}"

            return LLMResponse(
                Message(role="user", content=error_message, tool_calls=[])
            )

        except Exception as e:
            logger.error(f"Error getting LLM response: {e}")
            raise e

    @property
    def requires_answer_extraction(self) -> bool:
        """Whether :meth:`run_agent` runs the LiteLLM answer extractor.

        Most agents return raw reasoning output from :meth:`run`, so the base
        machinery makes a final, separate LiteLLM call to distil a clean answer.
        Agents whose :meth:`run` already returns a final, submit-ready answer
        (e.g. a black-box harness that extracts its own `Final Answer:`)
        override this to `False`. That both avoids an extra, separately-billed
        model call and guarantees the benchmark submits *exactly* the answer the
        harness produced instead of an extractor's paraphrase of it.
        """
        return True

    @abstractmethod
    def run(
        self,
        interface: CorralRouter,
        task_id: str,
        task_prompt: str | None = None,
        examples: list[str] | None = None,
        **kwargs,
    ) -> str:
        """
        Run the agent to solve a task

        This method must be implemented by all subclasses.

        If the agent was created via `from_trace()`, `self._initial_messages`
        will contain the conversation history and should be used instead of
        building a fresh prompt.

        Args:
            interface (BenchmarkInterface): The benchmark interface to use
            task_id (str): The task ID to solve
            task_prompt (str, optional): The task prompt to use. Defaults to None.
            examples (list[str], optional): List with the few-shot examples to use. Defaults to None.
            **kwargs: Additional keyword arguments that may include:
                - enable_surrender (bool): Whether to enable the surrender option. Defaults to False.
                  Only used by agents that support surrendering.

        Returns:
            str: The final answer from the agent
        """
        raise NotImplementedError("Subclasses must implement run_agent()")

    def run_agent(
        self,
        interface: CorralRouter,
        task_id: str,
        task_prompt: str | None = None,
        examples: list[str] | None = None,
        verbose: bool = False,
        tool_verbosity: str = "brief",
        enable_surrender: bool = False,
    ) -> AgentRunResult:
        """Run the agent to solve a task

        This method is a wrapper around run to provide a consistent interface

        Args:
            interface (BenchmarkInterface): The benchmark interface to use
            task_id (str): The task ID to solve
            task_prompt (str, optional): The task prompt to use. Defaults to None.
            examples (list[str], optional): List with the few-shot examples to use. Defaults to None.
            verbose (bool, optional): Whether to save agent messages. Defaults to False.
            tool_verbosity (str, optional): The verbosity level for tool information. Defaults to "brief".
            enable_surrender (bool, optional): Whether to enable the surrender option, which allows the agent to give up solving a task. Defaults to False.

        Returns:
            AgentRunResult: A dataclass with named fields for the final
                `answer`, the `messages` exchanged during the task, and the
                total `token_usage` information.
        """
        self.reset_token_usage()

        final_answer: str | None = None
        cancelled = False
        try:
            final_answer = self.run(
                interface,
                task_id,
                task_prompt,
                examples,
                enable_surrender=enable_surrender,
            )
            early = self._early_answer_result(task_id, final_answer)
            if early is not None:
                return early
        except BudgetExhaustedError:
            # Re-raise to stop the benchmark immediately
            raise
        except Exception:
            return self._run_exception_result()
        except BaseException:
            # Cancellation (Ctrl+C / anyio CancelledError, SystemExit, ...): the
            # trial is being abandoned and its result discarded, so its partial
            # transcript must not be persisted. Flag it so the `finally` skips the
            # verbose save, then let the cancellation propagate untouched.
            cancelled = True
            raise
        finally:
            if verbose and not cancelled:
                self._save_run_messages(task_id, tool_verbosity)

        # Agents that already return a submit-ready answer bypass the extra
        # answer-extraction model call so the benchmark measures (and submits)
        # exactly what the agent produced.
        if not self.requires_answer_extraction:
            return self._agent_run_result(final_answer)

        return self._extract_final_answer(final_answer)

    def _early_answer_result(
        self, task_id: str, final_answer: str
    ) -> AgentRunResult | None:
        """Turn a surrender/error answer into a terminal result, else `None`.

        Shared by the sync :meth:`run_agent` and async :meth:`arun_agent`. The
        surrender sentinel is returned verbatim (never through the answer
        extractor) so giving up never depends on an extra model call; every agent
        emits `SURRENDER_SENTINEL`, which is what CorralRunner checks before
        calling `surrender_task()`. An answer containing `"Error"` is likewise a
        harness-signalled failure surfaced as-is. Returning `None` means the run
        succeeded and the caller should proceed to (optional) answer extraction.
        """
        if final_answer == SURRENDER_SENTINEL:
            logger.info(f"Agent surrender from task {task_id}")
            return self._agent_run_result(final_answer)
        if "Error" in final_answer:
            logger.error(f"Error in agent response: {final_answer}")
            return self._agent_run_result(final_answer)
        return None

    def _run_exception_result(self) -> AgentRunResult:
        """Build the `agent_error` result for an exception escaping :meth:`run`.

        An exception escaping `run()` is never a real model answer, so it is
        marked as an infrastructure failure. `execute_single_trial` routes any
        non-submit-worthy status to the trial exception path instead of
        submitting the traceback string to the task scorer.
        """
        full_error = traceback.format_exc()
        logger.error(f"Error running agent: {full_error}")
        self.messages.append(
            LiteLLMMessage(role="user", content=f"Error running agent: {full_error}")
        )
        return AgentRunResult(
            answer=f"Error running agent: {full_error}",
            messages=self.messages,
            token_usage=self.get_total_token_usage(),
            status="agent_error",
            error_message=full_error,
        )

    def _save_run_messages(self, task_id: str, tool_verbosity: str) -> None:
        """Persist the run transcript when `verbose` was requested."""
        # Check if agent has stored tools information
        tools = getattr(self, "_available_tools", None)
        save_agent_messages(
            messages=self.messages,
            task_id=task_id,
            agent_name=self.__class__.__name__,
            model=self.model,
            tools=tools,
            tool_verbosity=tool_verbosity,
        )

    def _extract_final_answer(self, final_answer: str) -> AgentRunResult:
        """Run the LiteLLM answer extractor to distil a clean final answer.

        Only reached for agents whose :attr:`requires_answer_extraction` is
        `True`; the async path offloads this blocking call to a worker thread.
        """
        message = "The task is to:\n" + self.messages[0]["content"]
        if self.messages[0]["role"] == "system":
            message += "\n\n" + self.messages[1]["content"]
        message += f"\n\nAnd the answer provided by the model\n\n{self.messages[-1]['content']}"

        prompt = self.extractor_prompt.fill(
            {
                "answer": final_answer,
                "message": message,
            }
        )

        try:
            response = llm_call(
                model=self.model,
                messages=[LiteLLMMessage(role="user", content=prompt)],
                temperature=0.0,
                api_endpoint=self.api_endpoint,
                return_usage=False,  # No need for usage tracking in extractor
                **self.kwargs,
            )

            return self._agent_run_result(response.content)

        except Exception as e:
            logger.error(f"Error extracting final answer: {e}")
            return self._agent_run_result(final_answer)

    async def arun(
        self,
        interface: CorralRouter,
        task_id: str,
        task_prompt: str | None = None,
        examples: list[str] | None = None,
        enable_surrender: bool = False,
        **kwargs: Any,  # noqa: ARG002
    ) -> str:
        """Async counterpart of :meth:`run` — the seam native agents override.

        The default implementation offloads the synchronous :meth:`run` (and the
        blocking harness/HTTP work it drives) to a worker thread so an `anyio`
        scheduler can run many trials concurrently without blocking the event
        loop. Because that thread has **no** running event loop, an agent whose
        `run()` bridges an async SDK (e.g. via `asyncio.run`) takes its simple
        single-loop path rather than nesting an extra loop in yet another thread.

        Agents whose SDK is natively async (e.g. Claude Code) override this to
        `await` their coroutine directly on the scheduler loop, avoiding the
        thread/loop nesting entirely and enabling structured cancellation of the
        in-flight SDK call. Their synchronous :meth:`run` then becomes the
        wrapper. Returns the raw final answer string, exactly like :meth:`run`.

        The worker thread has no event loop, so a blocking :meth:`run` cannot
        drive an :class:`~corral.router.AsyncCorralRouter` (its methods would
        return un-awaited coroutines). :func:`as_sync_interface` hands `run` an
        equivalent **synchronous** router in that case; a synchronous interface
        is passed straight through, so the historical path is unchanged.
        """
        run_interface = as_sync_interface(interface)
        return await anyio.to_thread.run_sync(
            partial(
                self.run,
                run_interface,
                task_id,
                task_prompt,
                examples,
                enable_surrender=enable_surrender,
            )
        )

    async def arun_agent(
        self,
        interface: CorralRouter,
        task_id: str,
        task_prompt: str | None = None,
        examples: list[str] | None = None,
        verbose: bool = False,
        tool_verbosity: str = "brief",
        enable_surrender: bool = False,
    ) -> AgentRunResult:
        """Async counterpart of :meth:`run_agent`.

        Mirrors :meth:`run_agent` step for step but drives the agent through the
        async :meth:`arun` seam rather than the synchronous :meth:`run`. For a
        natively-async agent (e.g. Claude Code) the harness coroutine runs
        directly on the scheduler loop; for every other agent :meth:`arun`
        offloads the blocking `run()` to a worker thread. Either way the
        surrender/error handling, transcript saving, and result assembly are the
        *same* code paths the sync runner uses, so the two stay in lockstep.

        The (blocking) LiteLLM answer extractor — only invoked for agents whose
        :attr:`requires_answer_extraction` is `True` — is offloaded to a thread
        so it never stalls the event loop.

        Args and return value mirror :meth:`run_agent`.
        """
        self.reset_token_usage()

        final_answer: str | None = None
        cancelled = False
        try:
            final_answer = await self.arun(
                interface,
                task_id,
                task_prompt,
                examples,
                enable_surrender=enable_surrender,
            )
            early = self._early_answer_result(task_id, final_answer)
            if early is not None:
                return early
        except BudgetExhaustedError:
            # Re-raise to stop the benchmark immediately
            raise
        except Exception:
            return self._run_exception_result()
        except BaseException:
            # Cancellation (Ctrl+C / anyio CancelledError, SystemExit, ...): the
            # trial is being abandoned and its result discarded, so its partial
            # transcript must not be persisted. Flag it so the `finally` skips the
            # verbose save, then let the cancellation propagate untouched.
            cancelled = True
            raise
        finally:
            if verbose and not cancelled:
                self._save_run_messages(task_id, tool_verbosity)

        if not self.requires_answer_extraction:
            return self._agent_run_result(final_answer)

        return await anyio.to_thread.run_sync(
            partial(self._extract_final_answer, final_answer)
        )

    def _agent_run_result(self, answer: str) -> AgentRunResult:
        """Build an :class:`AgentRunResult`, propagating a harness status.

        Black-box harness agents (Codex, Claude Code, OpenHands) record a
        structured `HarnessRunResult` on `self.harness_result` with a precise
        terminal status. Surfacing that status (and its error/metadata) here lets
        :func:`~corral.run.execute_single_trial` route an infrastructure failure
        (timeout, SDK crash, MCP transport failure, budget/iteration exhaustion)
        to the trial exception path instead of submitting the harness's error
        string to the task scorer as if it were a model answer. Agents without a
        `harness_result` keep the default `"success"` status, so their behaviour
        is unchanged.
        """
        harness_result = getattr(self, "harness_result", None)
        status = "success"
        error_message: str | None = None
        metadata: dict[str, Any] = {}
        if harness_result is not None:
            status = getattr(harness_result, "status", "success") or "success"
            error_message = getattr(harness_result, "error", None)
            metadata = dict(getattr(harness_result, "metadata", {}) or {})
        return AgentRunResult(
            answer=answer,
            messages=self.messages,
            token_usage=self.get_total_token_usage(),
            status=status,
            error_message=error_message,
            metadata=metadata,
        )

    def _accumulate_token_usage(self, usage: dict[str, int]) -> None:
        """Add one LLM call's usage on top of the running run total.

        Sums `prompt_tokens`/`completion_tokens`/`total_tokens` into
        `cumulative_token_usage` so the totals grow over the conversation
        instead of being replaced by each call's usage.
        """
        for key in ("prompt_tokens", "completion_tokens", "total_tokens"):
            self.cumulative_token_usage[key] = self.cumulative_token_usage.get(
                key, 0
            ) + int(usage.get(key, 0) or 0)

    def get_total_token_usage(self) -> dict[str, int]:
        """Calculate total token usage across all LLM calls in the run

        Returns:
            dict[str, int]: Dictionary with prompt_tokens, completion_tokens, and total_tokens
        """
        total_prompt_tokens = self.cumulative_token_usage.get("prompt_tokens", 0)
        total_completion_tokens = self.cumulative_token_usage.get(
            "completion_tokens", 0
        )
        total_tokens = self.cumulative_token_usage.get("total_tokens", 0)

        return {
            "prompt_tokens": total_prompt_tokens,
            "completion_tokens": total_completion_tokens,
            "total_tokens": total_tokens,
        }

    def reset_token_usage(self) -> None:
        """Reset token usage tracking"""
        self.token_usage = {}
        self.cumulative_token_usage = {}

    def _execute_hooks(
        self,
        hook_point: HookPoint,
        interface: CorralRouter,
        task_id: str,
        **extra_context,
    ) -> HookContext:
        """Execute hooks at a specific point in agent lifecycle.

        This is a helper method that creates a HookContext and executes
        all registered hooks for the given hook point.

        Args:
            hook_point: The lifecycle point to execute hooks for
            interface: The router interface
            task_id: The current task ID
            **extra_context: Additional context fields to include

        Returns:
            The hook context (potentially modified by hooks)
        """
        context = HookContext(
            task_id=task_id,
            agent=self,
            interface=interface,
            messages=self.messages,
            iteration=self._current_iteration,
            iteration_data=extra_context,
        )
        return self.hooks.execute(hook_point, context)
