import importlib.resources
from abc import ABC, abstractmethod
from typing import Any

from litellm.exceptions import ContextWindowExceededError
from litellm.types.utils import Message
from loguru import logger
from promptstore import PromptStore

from corral.agents.prompt_utils import ensure_jinja_compatible, get_prompt
from corral.agents.utils import (
    LiteLLMMessage,
    count_tokens_and_add,
    llm_call,
    save_agent_messages,
)
from corral.router.routes import CorralRouter


class BaseAgent(ABC):
    """
    Base Agent class that captures common functionality for different agent types.

    This abstract base class provides common initialization parameters and methods
    for agent implementations.

    ## Prompt System Overview

    ### Prompt Types:
    - **system_prompt**: Sets the agent's behavior and role (e.g., "You are a helpful AI assistant")
    - **user_prompt**: Contains the main task instructions with placeholders for dynamic content
    - **extractor_prompt**: Used to extract and clean final answers from agent responses.
      This prompt takes the raw agent output and extracts just the answer portion, removing
      explanatory text, formatting artifacts, or multiple choice options.
    - **surrender_prompt**: Instructions for how the agent can surrender from unsolvable tasks.
      This prompt is only included when enable_surrender=True in the run() method and will be added to the task prompt.


    Depending of the agent type, different user_prompt templates are required with specific
    placeholders and formatting instructions.

    Args:
        model (str): The model to use for running the agent. Defaults to "openai/gpt-4o".
        max_iterations (int, optional): The maximum number of iterations (number of LLM calls) to run. Defaults to 10.
        api_endpoint (str, optional): The API endpoint URL for the LLM provider
            (e.g., OpenAI, VLLM, or self-hosted models) to handle requests. Defaults to None meaning that it uses LiteLLM.
        system_prompt (str | Any, optional): The system prompt to use. Must be an string.
            If None, uses default system prompt.
        user_prompt (str | Any, optional): The user prompt to use. Must be an string with the different variables required by each agent.
            If None, uses default prompt specific to each agent type.
        extractor_prompt (str | Any, optional): The extractor prompt for cleaning final answers.
            If None, uses default extractor prompt with ID "9d37e4a0-26c5-438a-ba1b-a273388fcded".
            Must be a string that supports the next variables:
                - `answer`: The raw answer generated by the agent
                - `message`: The full message context including task description and agent response
        surrender_prompt (str | Any, optional): The surrender prompt with instructions for surrendering (When agent cannot solve a task, it can give up by following this instruction). Can be a string or prompt object that implements .fill() method. Must support Jinja templating.
        temperature (float, optional): The temperature to use for sampling. Defaults to 0.7.
        surrender_prompt_id (str, optional): The ID of the surrender prompt to use from the prompt store.
            Defaults to None (each agent type has its own default).
        **kwargs: Additional keyword arguments to pass to the LiteLLM API
    """

    def __init__(
        self,
        model: str = "openai/gpt-4o",
        max_iterations: int = 10,
        api_endpoint: str | None = None,
        system_prompt: str | Any | None = None,
        user_prompt: str | Any | None = None,
        extractor_prompt: str | Any | None = None,
        surrender_prompt: str | Any | None = None,
        temperature: float = 0.7,
        surrender_prompt_id: str | None = None,
        **kwargs,
    ):
        """Initialize the base agent with common parameters"""
        self.model = model
        self.max_iterations = max_iterations
        self.api_endpoint = api_endpoint
        self.temperature = temperature
        self.messages: list = []
        self.token_usage: dict = {}  # Track token usage per LLM call

        with importlib.resources.path("corral.agents", "") as style_path:
            self.store = PromptStore(f"{style_path}/prompts")

        self.kwargs = kwargs

        # Default prompt IDs
        default_system_prompt_id = "400fcecf-f5f2-464b-aff5-8a4377c9685c"
        default_extractor_prompt_id = "9d37e4a0-26c5-438a-ba1b-a273388fcded"

        # Handle system prompt - convert to string immediately as it typically doesn't need variables
        if system_prompt is None:
            self.system_prompt = get_prompt(
                self.store, None, default_system_prompt_id
            ).fill({})
        else:
            system_prompt_obj = ensure_jinja_compatible(system_prompt)
            self.system_prompt = system_prompt_obj.fill({})

        # Handle user prompt (subclasses should set their default)
        if user_prompt is None:
            self.user_prompt = None
        else:
            self.user_prompt = ensure_jinja_compatible(user_prompt)

        # Handle extractor prompt
        if extractor_prompt is None:
            self.extractor_prompt = get_prompt(
                self.store, extractor_prompt, default_extractor_prompt_id
            )
        else:
            self.extractor_prompt = ensure_jinja_compatible(extractor_prompt)

        if surrender_prompt_id and surrender_prompt is None:
            self.surrender_prompt = get_prompt(
                self.store, surrender_prompt, surrender_prompt_id
            )
        else:
            self.surrender_prompt = surrender_prompt

    def get_llm_response(self, tools: list[dict[str, Any]] | None = None) -> Any:
        """Get response from the LLM using LiteLLM

        Args:
            tools (dict[str, Any], optional): Optional tools/functions for function calling

        Returns:
            Any: The response from the LLM
        """
        self.messages = count_tokens_and_add(
            self.messages, self.model, self.token_usage.get("total_tokens", 0)
        )
        try:
            response, usage_info = llm_call(
                model=self.model,
                messages=self.messages,
                tools=tools,
                temperature=self.temperature,
                api_endpoint=self.api_endpoint,
                return_usage=True,
                **self.kwargs,
            )

            # Track token usage
            self.token_usage = usage_info

            return response

        except ContextWindowExceededError as e:
            logger.error(f"API error: {e}")

            for message in reversed(self.messages):
                if message["role"] != "assistant":
                    if "content" in message:
                        content = str(message["content"])
                        if len(content) > 100:
                            message["content"] = content[:100] + "..."
                else:
                    break

            error_message = f"{type(e).__name__}: {e!s}"

            return Message(role="user", content=error_message, tool_calls=[])

        except Exception as e:
            logger.error(f"Error getting LLM response: {e}")
            raise e

    @abstractmethod
    def run(
        self,
        interface: CorralRouter,
        task_id: str,
        history: list[LiteLLMMessage] | None = None,
        task_prompt: str | None = None,
        examples: list[str] | None = None,
        enable_surrender: bool = False,
    ) -> str:
        """
        Run the agent to solve a task

        This method must be implemented by all subclasses

        Args:
            interface (BenchmarkInterface): The benchmark interface to use
            task_id (str): The task ID to solve
            history (list[LiteLLMMessage], optional): The history items to include. Defaults to None.
            task_prompt (str, optional): The task prompt to use. Defaults to None.
            examples (list[str], optional): List with the few-shot examples to use. Defaults to None.
            enable_surrender (bool, optional): Whether to enable the surrender option, which allows the agent to give up solving a task. Defaults to False.

        Returns:
            str: The final answer from the agent
        """
        raise NotImplementedError("Subclasses must implement run_agent()")

    def run_agent(
        self,
        interface: CorralRouter,
        task_id: str,
        history: list[LiteLLMMessage] | None = None,
        task_prompt: str | None = None,
        examples: list[str] | None = None,
        verbose: bool = False,
        tool_verbosity: str = "brief",
        enable_surrender: bool = False,
    ) -> tuple[str, dict[str, int]]:
        """Run the agent to solve a task

        This method is a wrapper around run to provide a consistent interface

        Args:
            interface (BenchmarkInterface): The benchmark interface to use
            task_id (str): The task ID to solve
            history (list[LiteLLMMessage], optional): The history items to include. Defaults to None.
            task_prompt (str, optional): The task prompt to use. Defaults to None.
            examples (list[str], optional): List with the few-shot examples to use. Defaults to None.
            verbose (bool, optional): Whether to save agent messages. Defaults to False.
            tool_verbosity (str, optional): The verbosity level for tool information. Defaults to "brief".
            enable_surrender (bool, optional): Whether to enable the surrender option, which allows the agent to give up solving a task. Defaults to False.

        Returns:
            str: The final answer from the agent
        """
        self.reset_token_usage()

        if history is None:
            history = []

        try:
            final_answer = self.run(
                interface, task_id, history, task_prompt, examples, enable_surrender
            )

            # Check if agent decided to surrender
            if final_answer == "GIVE UP":
                logger.info(f"Agent surrender from task {task_id}")
                return "GIVE UP", self.get_total_token_usage()

            if verbose:
                # Check if agent has stored tools information
                tools = getattr(self, "_available_tools", None)
                save_agent_messages(
                    messages=self.messages,
                    task_id=task_id,
                    agent_name=self.__class__.__name__,
                    model=self.model,
                    tools=tools,
                    tool_verbosity=tool_verbosity,
                )

            if "Error" in final_answer:
                logger.error(f"Error in agent response: {final_answer}")
                return final_answer, self.get_total_token_usage()

        except Exception as e:
            logger.error(f"Error running agent: {e}")
            return f"Error running agent: {e}", self.get_total_token_usage()

        message = "The task is to:\n" + self.messages[0]["content"]
        if self.messages[0]["role"] == "system":
            message += "\n\n" + self.messages[1]["content"]
        message += f"\n\nAnd the answer provided by the model\n\n{self.messages[-1]['content']}"

        prompt = self.extractor_prompt.fill(
            {
                "answer": final_answer,
                "message": message,
            }
        )

        try:
            answer = llm_call(
                model=self.model,
                messages=[LiteLLMMessage(role="user", content=prompt)],
                temperature=0.0,
                api_endpoint=self.api_endpoint,
                **self.kwargs,
            )

            return answer.content, self.get_total_token_usage()

        except Exception as e:
            logger.error(f"Error extracting final answer: {e}")
            return final_answer, self.get_total_token_usage()

    def get_total_token_usage(self) -> dict[str, int]:
        """Calculate total token usage across all LLM calls

        Returns:
            dict[str, int]: Dictionary with prompt_tokens, completion_tokens, and total_tokens
        """
        total_prompt_tokens = self.token_usage.get("prompt_tokens", 0)
        total_completion_tokens = self.token_usage.get("completion_tokens", 0)
        total_tokens = self.token_usage.get("total_tokens", 0)

        return {
            "prompt_tokens": total_prompt_tokens,
            "completion_tokens": total_completion_tokens,
            "total_tokens": total_tokens,
        }

    def reset_token_usage(self) -> None:
        """Reset token usage tracking"""
        self.token_usage = {}
