from corral.agents.base_agent import BaseAgent
from corral.agents.prompt_utils import create_prompt
from corral.agents.react import ReActAgent
from corral.agents.tool_calling import ToolCallingAgent
from corral.agents.utils import LiteLLMMessage
from corral.router.routes import CorralRouter


class LLMPlanner(BaseAgent):
    """
    Agent that uses hierarchical planning to solve tasks.
    Based on https://arxiv.org/abs/2212.04088

    The LLMPlanner works in two stages:
    1. **High-level planning**: Generates step-by-step plans using the LLM
    2. **Low-level execution**: Delegates plan execution to ReActAgent or ToolCallingAgent

    This approach allows for better task decomposition and more structured problem-solving.

    ### Default User Prompt Template:
    The default prompt ("src/corral/agents/prompts/planner_prompt/user_prompt/prompt.md") expects:

    ### Custom Prompt Requirements:
    If providing a custom user_prompt, it must:
    1. Include {{task_guide}} placeholder for task instructions
    2. Include {{tools}} placeholder for available tools (JSON format)
    3. Include {{iterations}} placeholder for iteration limit
    4. Include {{examples}} placeholder for few-shot examples
    5. Instruct the agent to create step-by-step plans
    6. Specify "Final Answer:" format for completion

    Args:
        model (str): The model to use for running the agent. Defaults to "openai/gpt-4o".
        max_iterations (int, optional): The maximum number of iterations (number of LLM calls) to run. Defaults to 10.
        api_endpoint (str, optional): The API endpoint URL for the LLM provider
            (e.g., OpenAI, VLLM, or self-hosted models) to handle requests. Defaults to None meaning that it uses LiteLLM.
        system_prompt (str, optional): The system prompt to use. Must be an string.
            If None, uses default system prompt at "src/corral/agents/prompts/system_prompt/system_prompt/prompt.md".
        user_prompt (str, optional): The user prompt to use. Must be an string with the different variables required by each agent.
            If None, uses default prompt "src/corral/agents/prompts/planner_prompt/user_prompt/prompt.md".
            Must be a string that supports the next variables:
            - `task_guide`: The task instructions to solve the task
            - `tools`: The available tools in JSON format
            - `iterations`: The maximum number of iterations allowed
            - `examples`: Few-shot examples to guide the agent
        extractor_prompt (str, optional): The extractor prompt for cleaning final answers.
            If None, uses default extractor prompt at "src/corral/agents/prompts/extractor_prompt/extractor_prompt/prompt.md".
            Must be a string that supports the next variables:
                - `answer`: The raw answer generated by the agent
                - `message`: The full message context including task description and agent response
        surrender_prompt (str, optional): The surrender prompt with instructions for surrendering.
            This is, when the agent cannot solve a task, it can give up by following this instruction.
            Must be a string.
        temperature (float, optional): The temperature to use for sampling. Defaults to 0.7.
        **kwargs: Additional keyword arguments to pass to the LiteLLM API
    """

    def __init__(
        self,
        model: str = "openai/gpt-4o",
        max_iterations: int = 10,
        api_endpoint: str | None = None,
        system_prompt: str | None = None,
        user_prompt: str | None = None,
        extractor_prompt: str | None = None,
        temperature: float = 0.7,
        **kwargs,
    ):
        """Initialize the agent"""
        # Set default user prompt if not provided
        if user_prompt is None:
            user_prompt = "planner_prompt/user_prompt"

        super().__init__(
            model=model,
            max_iterations=max_iterations,
            api_endpoint=api_endpoint,
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            extractor_prompt=extractor_prompt,
            temperature=temperature,
            **kwargs,
        )

    def run(
        self,
        interface: CorralRouter,
        task_id: str,
        task_prompt: str | None = None,
        examples: list[str] | None = None,
        **kwargs,  # noqa: ARG002
    ) -> str:
        """Run the LLM planner agent

        Args:
            interface (CorralRouter): The benchmark interface to use
            task_id (str): The task ID to solve
            task_prompt (str, optional): The task prompt to use. Defaults to None.
            examples (List[str], optional): List with the few-shot examples to use. Defaults to None.
            **kwargs: Additional keyword arguments (e.g., enable_surrender - not used by this agent)

        Returns:
            str: The final answer to the task
        """
        tools = interface.get_available_tools_for_task(task_id)

        tool_usage = (
            False  # Default to False, could be passed as a parameter in the future
        )

        if self._initial_messages is not None:
            self.messages = list(self._initial_messages)
        else:
            if task_prompt is None:
                task_guide = interface.get_task_prompt(task_id)
            else:
                task_guide = task_prompt

            self.messages = create_prompt(
                system_prompt=self.system_prompt,
                user_prompt=self.user_prompt,
                task_guide=task_guide,
                max_iterations=self.max_iterations,
                examples=examples,
                tools=tools,
            )

        if tool_usage:
            agent = ToolCallingAgent(
                model=self.model,
                max_iterations=self.max_iterations,
                api_endpoint=self.api_endpoint,
                temperature=self.temperature,
                prompt_store=self.store,
                **self.kwargs,
            )
        else:
            agent = ReActAgent(
                model=self.model,
                max_iterations=self.max_iterations,
                api_endpoint=self.api_endpoint,
                temperature=self.temperature,
                prompt_store=self.store,
                **self.kwargs,
            )

        for _i in range(self.max_iterations):
            response = self.get_llm_response()
            plan = response.content

            self.messages.append(
                LiteLLMMessage(
                    role="assistant",
                    content=plan,
                    name="high-level-planner",
                    id=response.id,
                )
            )
            if plan is None:
                continue

            if "Final Answer:" in plan:
                return plan.split("Final Answer:")[1].strip()

            final_answer = agent.run(
                interface=interface,
                task_id=task_id,
                task_prompt=plan,
            )

            self.messages.append(
                LiteLLMMessage(
                    role="assistant",
                    content=f"Answer submitted by the executor: {final_answer}.\nMessages by the executor:",
                    name="low-level-planner",
                )
            )
            self.messages.extend(agent.messages)
            agent.messages.clear()

        self.messages.append(
            LiteLLMMessage(
                role="assistant",
                content="Error: Maximum iterations reached without finding a final answer.",
                name="planner-error",
            )
        )
        return "Error: Maximum iterations reached"
