import json
import re

from loguru import logger

from corral.agents.base_agent import BaseAgent
from corral.agents.hooks import HookPoint
from corral.agents.prompt_utils import create_prompt
from corral.agents.schema import Action, Thought
from corral.agents.utils import LiteLLMMessage, convert_outermost_triple_quotes
from corral.router.routes import CorralRouter


class ReActAgent(BaseAgent):
    """
    Agent that uses the ReAct framework to solve tasks.
    Based on https://arxiv.org/abs/2210.03629

    The ReAct agent follows a "Thought-Action-Observation" loop, where it reasons about
    the task, executes tools, and observes results before continuing to the next step.

    ### Default User Prompt Template:
    The default prompt ("src/corral/agents/prompts/react/user_prompt/prompt.md") expects:

    ### Custom Prompt Requirements:
    If providing a custom user_prompt, it must:
    1. Include {{task_guide}} placeholder for task instructions
    2. Include {{examples}} placeholder for few-shot examples
    3. Instruct the agent to use "Thought:", "Action:", "Action Input:" format
    4. Specify "Final Answer:" format for completion


    Args:
        model (str): The model to use for running the agent. Defaults to "openai/gpt-4o".
        max_iterations (int, optional): The maximum number of iterations (number of LLM calls) to run. Defaults to 10.
        api_endpoint (str, optional): The API endpoint URL for the LLM provider
            (e.g., OpenAI, VLLM, or self-hosted models) to handle requests. Defaults to None meaning that it uses LiteLLM.
        system_prompt (str, optional): The system prompt to use. Must be an string.
            If None, uses default system prompt at "src/corral/agents/prompts/system_prompt/system_prompt/prompt.md".
        user_prompt (str, optional): The user prompt to use. Must be an string with the different variables required by each agent.
            If None, uses default prompt "src/corral/agents/prompts/react/user_prompt/prompt.md".
            Must be a string that supports the next variables:
                - `task_guide`: The task description or plan
                - `examples`: Few-shot examples to guide the agent
                - `surrender_instructions`: Instructions for surrendering, if enabled
        extractor_prompt (str, optional): The extractor prompt for cleaning final answers.
            If None, uses default extractor prompt at "src/corral/agents/prompts/extractor_prompt/extractor_prompt/prompt.md".
            Must be a string that supports the next variables:
                - `answer`: The raw answer generated by the agent
                - `message`: The full message context including task description and agent response
        surrender_prompt (str, optional): The surrender prompt with instructions for surrendering.
            This is, when the agent cannot solve a task, it can give up by following this instruction.
            Must be a string.
        temperature (float, optional): The temperature to use for sampling. Defaults to 0.7.
        **kwargs: Additional keyword arguments to pass to the LiteLLM API
    """

    def __init__(
        self,
        model: str = "openai/gpt-4o",
        max_iterations: int = 10,
        api_endpoint: str | None = None,
        system_prompt: str | None = None,
        user_prompt: str | None = None,
        extractor_prompt: str | None = None,
        surrender_prompt: str | None = None,
        temperature: float = 0.7,
        **kwargs,
    ):
        """Initialize the agent"""
        # Set default user prompt if not provided
        if user_prompt is None:
            user_prompt = "react/user_prompt"

        super().__init__(
            model=model,
            max_iterations=max_iterations,
            api_endpoint=api_endpoint,
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            extractor_prompt=extractor_prompt,
            surrender_prompt=surrender_prompt,
            temperature=temperature,
            **kwargs,
        )

    def parse_llm_response(
        self, response: str
    ) -> tuple[list[Thought] | None, list[Action] | None]:
        """Parse LLM response into Thoughts and Actions"""
        thought_matches = re.finditer(r"<thought>(.*?)</thought>", response, re.DOTALL)
        action_matches = re.finditer(
            r"<action>(.*?)</action>(?:.*?<action_input>(.*?)</action_input>)?",
            response,
            re.DOTALL,
        )

        thoughts = [Thought(match.group(1).strip()) for match in thought_matches]

        actions = []
        for action_match in action_matches:
            tool_name = action_match.group(1).strip()
            try:
                action_input = action_match.group(2)
                # Check if action_input tags are malformed (opening tag present but closing tag missing)
                if action_input is None:
                    return thoughts, None
                else:
                    action_input = action_match.group(2).strip()

                converted_input = convert_outermost_triple_quotes(action_input)

                # Handle Python boolean values
                converted_input = converted_input.replace("True", "true").replace(
                    "False", "false"
                )

                # Convert tuples to lists for color mixing in wetlab
                if tool_name == "simulate_color_mixture":
                    converted_input = converted_input.replace("(", "[").replace(
                        ")", "]"
                    )

                # Parse as JSON
                arguments = json.loads(converted_input)
                actions.append(Action(tool_name=tool_name, arguments=arguments))
            except (json.JSONDecodeError, ValueError, SyntaxError) as e:
                logger.error(f"Parsing error: {e}")

        return thoughts if thoughts else None, actions if actions else None

    def run(
        self,
        interface: CorralRouter,
        task_id: str,
        task_prompt: str | None = None,
        examples: list[str] | None = None,
        enable_surrender: bool = False,
        **kwargs,  # noqa: ARG002
    ) -> str:
        """Main ReAct loop implementation

        Args:
            interface (CorralRouter): The interface to use
            task_id (str): The task ID to solve
            task_prompt (str, optional): The task prompt to use. `task_prompt` is intended to be a plan or description about the task, that should always be provided when this agent is called as a subagent of a main orchestrator. Defaults to None.
            examples (List[str], optional): List with the few-shot examples to use. Defaults to None.
            enable_surrender (bool, optional): Whether to enable the surrender option, which allows the agent to give up solving a task. Defaults to False.

        Returns:
            str: The final answer to the task
        """
        if self._initial_messages is not None:
            self.messages = list(self._initial_messages)
        else:
            if task_prompt is None:
                task_guide = interface.get_task_guide(task_id)
            else:
                task_guide = task_prompt

            self.messages = create_prompt(
                system_prompt=self.system_prompt,
                user_prompt=self.user_prompt,
                task_guide=task_guide,
                examples=examples,
                surrender_prompt=self.surrender_prompt,
                enable_surrender=enable_surrender,
            )

        # Execute BEFORE_TASK hooks
        self._execute_hooks(HookPoint.BEFORE_TASK, interface, task_id)

        for _iteration in range(self.max_iterations):
            self._current_iteration = _iteration

            # Execute BEFORE_ITERATION hooks
            self._execute_hooks(HookPoint.BEFORE_ITERATION, interface, task_id)
            # Create prompt and get LLM response
            full_llm_response = self.get_llm_response()
            llm_response = full_llm_response.content

            self.messages.append(
                LiteLLMMessage(
                    role="assistant", content=llm_response, id=full_llm_response.id
                )
            )

            # Parse response
            _thoughts, actions = self.parse_llm_response(llm_response)

            # Check for surrender (XML format) if enabled
            if enable_surrender and (
                surrender_match := re.search(
                    r"<surrender>(.*?)</surrender>",
                    llm_response,
                    re.DOTALL | re.IGNORECASE,
                )
            ):
                logger.info(
                    f"Agent surrendering from task {task_id}. Reason: {surrender_match[1].strip()}"
                )
                return "SURRENDER"

            # Check for final answer (XML format)
            final_answer_match = re.search(
                r"<final_answer>(.*?)</final_answer>", llm_response, re.DOTALL
            ) or re.search(r"Final Answer: (.*)", llm_response, re.DOTALL)

            # Execute tools if actions exist
            if actions:
                # Check for final answer
                for action in actions:
                    # Execute tool and get response
                    tool_response = interface.execute_tool(
                        task_id, action.tool_name, action.arguments
                    )

                    observation = (
                        f"Observation: {tool_response.result}"
                        if tool_response.success
                        else f"Error: {tool_response.error}"
                    )

                    self.messages.append(
                        LiteLLMMessage(
                            role="user",
                            content=observation,
                            name=action.tool_name,
                        )
                    )

            self._execute_hooks(
                HookPoint.AFTER_ITERATION,
                interface,
                task_id,
                llm_response=full_llm_response,
            )
            if final_answer_match:
                return final_answer_match.group(1).strip()

            if not actions and final_answer_match is None:
                self.messages.append(
                    LiteLLMMessage(
                        role="user",
                        content="No actions to execute. This is due to parsing error or missing action in the response. Please follow the format <thought>[your reasoning]</thought>\n<action>[tool name]</action>\n<action_input>[tool arguments as JSON]</action_input>.\n\nIf you have the final answer, respond with:\n<thought>[your reasoning]</thought>\n<final_answer>[answer]</final_answer>. For tool calls without arguments, use `<action_input>{}</action_input>`. Remember the closing tags. Try again.",
                    )
                )

        self.messages.append(
            LiteLLMMessage(
                role="assistant",
                content="Error: Maximum iterations reached without finding a final answer.",
                name="react-error",
            )
        )

        return "Error solving the task: unable to complete it in the iteration limit"
