import json
import re

from loguru import logger

from corral.agents.base_agent import BaseAgent
from corral.agents.hooks import HookPoint
from corral.agents.prompt_utils import create_prompt
from corral.agents.schema import Action
from corral.agents.utils import (
    LiteLLMMessage,
    convert_to_openai_tool_format,
)
from corral.router.routes import CorralRouter


class ToolCallingAgent(BaseAgent):
    """
    Agent that uses native function calling from LLM providers to solve tasks.

    This agent leverages the built-in tool/function calling capabilities of modern LLMs
    (like OpenAI's function calling) rather than parsing text-based tool invocations.
    Tools are automatically made available to the LLM and called directly through the API.

    ### Default User Prompt Template:
    The default prompt ("src/corral/agents/prompts/tool_calling/user_prompt/prompt.md") expects:

    ### Custom Prompt Requirements:
    If providing a custom user_prompt, it must:
    1. Include {{task_guide}} placeholder for task instructions
    2. Include {{examples}} placeholder for few-shot examples
    3. Instruct the agent to indicate completion with "Final Answer:" format
    4. NOT include tool descriptions (tools are provided via function calling API)

    Args:
        model (str): The model to use for running the agent. Defaults to "openai/gpt-4o".
        max_iterations (int, optional): The maximum number of iterations (number of LLM calls) to run. Defaults to 10.
        api_endpoint (str, optional): The API endpoint URL for the LLM provider
            (e.g., OpenAI, VLLM, or self-hosted models) to handle requests. Defaults to None meaning that it uses LiteLLM.
        system_prompt (str, optional): The system prompt to use. Must be an string.
            If None, uses default system prompt at "src/corral/agents/prompts/system_prompt/system_prompt/prompt.md".
        user_prompt (str, optional): The user prompt to use. Must be an string with the different variables required by each agent.
            If None, uses default prompt "src/corral/agents/prompts/tool_calling/user_prompt/prompt.md".
            Must be a string that supports the next variables:
            - `task_guide`: The task instructions to solve the task (without tool descriptions)
            - `surrender_instructions`: Instructions for how the agent can surrender from unsolvable tasks.
        extractor_prompt (str, optional): The extractor prompt for cleaning final answers.
            If None, uses default extractor prompt at "src/corral/agents/prompts/extractor_prompt/extractor_prompt/prompt.md".
            Must be a string that supports the next variables:
                - `answer`: The raw answer generated by the agent
                - `message`: The full message context including task description and agent response
        surrender_prompt (str, optional): The surrender prompt with instructions for surrendering.
            This is, when the agent cannot solve a task, it can give up by following this instruction.
            Must be a string.
        temperature (float, optional): The temperature to use for sampling. Defaults to 0.7.
        **kwargs: Additional keyword arguments to pass to the LiteLLM API
    """

    def __init__(
        self,
        model: str = "openai/gpt-4o",
        max_iterations: int = 10,
        api_endpoint: str | None = None,
        system_prompt: str | None = None,
        user_prompt: str | None = None,
        extractor_prompt: str | None = None,
        surrender_prompt: str | None = None,
        temperature: float = 0.7,
        **kwargs,
    ):
        """Initialize the agent"""
        # Set default user prompt if not provided
        if user_prompt is None:
            user_prompt = "tool_calling/user_prompt"

        super().__init__(
            model=model,
            max_iterations=max_iterations,
            api_endpoint=api_endpoint,
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            extractor_prompt=extractor_prompt,
            surrender_prompt=surrender_prompt,
            temperature=temperature,
            **kwargs,
        )

        # Initialize available tools for logging
        self._available_tools = None

    def run(
        self,
        interface: CorralRouter,
        task_id: str,
        history: list[LiteLLMMessage] | None = None,
        task_prompt: str | None = None,
        examples: list[str] | None = None,
        enable_surrender: bool = False,
        **kwargs,  # noqa: ARG002
    ) -> str:
        """Run the agent to solve the task

        Args:
            interface (CorralRouter): The interface to use
            task_id (str): The task ID to solve
            history (list[LiteLLMMessage]], optional): The history items to include. Defaults to None.
            task_prompt (str, optional): The task prompt to use. Defaults to None.
            examples (list[str], optional): List with the few-shot examples to use. Defaults to None.
            enable_surrender (bool, optional): Whether to enable the surrender option, which allows the agent to give up solving a task. Defaults to False.

        Returns:
            str: The final answer to the task
        """
        tools = convert_to_openai_tool_format(
            interface.get_available_tools_for_task(task_id)
        )
        # Store tools for logging
        self._available_tools = tools

        if task_prompt is None:
            task_guide = interface.get_task_prompt(task_id)
        else:
            task_guide = task_prompt

        self.messages = create_prompt(
            system_prompt=self.system_prompt,
            user_prompt=self.user_prompt,
            task_guide=task_guide,
            history=history,
            examples=examples,
            surrender_prompt=self.surrender_prompt,
            enable_surrender=enable_surrender,
        )

        # Execute BEFORE_TASK hooks
        self._execute_hooks(HookPoint.BEFORE_TASK, interface, task_id)

        for _i in range(self.max_iterations):
            self._current_iteration = _i

            # Execute BEFORE_ITERATION hooks
            self._execute_hooks(HookPoint.BEFORE_ITERATION, interface, task_id)
            full_llm_response = self.get_llm_response()
            llm_response = full_llm_response.content
            try:
                llm_response = self.get_llm_response(tools)

                content = llm_response.content
                if content:
                    # Check for surrender if enabled
                    if enable_surrender:
                        surrender_match = re.search(
                            r"(?:Final Answer:\s*)?SURRENDER", content, re.IGNORECASE
                        )
                        if surrender_match:
                            logger.info(f"Agent retiring from task {task_id}")
                            self.messages.append(
                                LiteLLMMessage(role="assistant", content=content)
                            )
                            return "GIVE UP"

                    final_answer_match = re.search(
                        r"Final Answer:\s*(.*)", content, re.IGNORECASE
                    )
                    self._execute_hooks(
                        HookPoint.AFTER_ITERATION,
                        interface,
                        task_id,
                        llm_response=full_llm_response,
                    )
                    if final_answer_match:
                        self.messages.append(
                            LiteLLMMessage(role="assistant", content=content)
                        )
                        return final_answer_match.group(1).strip()

                tool_calls = llm_response.tool_calls
                if tool_calls:
                    self.messages.append(llm_response)

                    for called_tool in tool_calls:
                        # Initialize variables for error handling
                        result = None
                        function_name = str(called_tool.function.name)

                        try:
                            # Parse arguments - this can fail
                            raw_arguments = json.loads(called_tool.function.arguments)

                            # Create action
                            action = Action(
                                tool_name=called_tool.function.name,
                                arguments=raw_arguments,
                            )

                            # Execute tool - this can also fail
                            function_call = interface.execute_tool(
                                task_id, action.tool_name, action.arguments
                            )

                            result = str(function_call.result)
                            if result is None:
                                result = str(function_call.error)

                        except json.JSONDecodeError as e:
                            result = f"Error parsing tool arguments: {e!s}"
                            logger.error(
                                f"JSON parsing error for tool {function_name}: {e}"
                            )
                        except Exception as e:
                            result = f"Error executing tool: {e!s}"
                            logger.error(
                                f"Tool execution error for {function_name}: {e}"
                            )

                        self.messages.append(
                            LiteLLMMessage(
                                role="tool",
                                tool_call_id=called_tool.id,
                                content=result or "Unknown error occurred",
                                name=function_name,
                            )
                        )
                else:
                    self.messages.append(
                        LiteLLMMessage(role="assistant", content=llm_response.content)
                    )
            except Exception as e:
                # Append error message but continue with the next iteration
                logger.error(f"Error during agent iteration: {e}")
                self.messages.append(
                    LiteLLMMessage(
                        role="system",
                        content=f"Error during agent iteration: {e!s}",
                    )
                )

        self.messages.append(
            LiteLLMMessage(
                role="assistant",
                content="Error: Maximum iterations reached without finding a final answer.",
                name="tool-calling-error",
            )
        )

        return "Error solving the task. Maximum iterations reached."
