[project]
name = "chembench"
version = "0.1.0"
description = "Q&A Environment based in ChemBench"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chembench",
    "corral",
    "modal",
    "tenacity",
    "loguru",
    "rdkit",
    "langchain-community",
    "chromadb",
    "beautifulsoup4",
    "scikit-learn",
    "uvicorn>=0.34.0",
]

[tool.uv.sources]
chembench = { git = "https://github.com/lamalab-org/chembench.git", rev = "topic_wise_bench" }
corral = { git = "https://github.com/lamalab-org/mat-agent-bench.git", rev = "main" }
