[project]
name = "kinetic_modeling"
version = "0.1.0"
description = "Rate Law environment for the corral simulation agent benchmark framework."
readme = "README.md"
license = "MIT"
authors = [{ name = "Chandan Gupta", email = "chandan18386@iiitd.ac.in" }]
keywords = ["agent", "LLM", "benchmark"]
requires-python = ">=3.11"
dependencies = [
    "corral",
    "modal==0.70",
    "protobuf==3.20.*",
    "rich>=13.9.4",
    "pypdf",
    "more-itertools",
    "hypothesis>=6.136.0",
    "pytest-cov>=6.2.1",
    "pytest>=8.4.1",
    "pytest-mock>=3.14.1",
    "streamlit>=1.46.1"
]
[tool.uv.sources]
corral = { path = "../..", editable = true }
