Species:
# Base Species
  H+:
    Name: H+
    Formula: H+
    Elements: 1:H
    Charge: 1
    AggregateState: Aqueous
    StandardThermoModel:
      Constant:
        G0: 0.0
  
  OH-:
    Name: OH-
    Formula: OH-
    Elements: 1:O 1:H
    Charge: -1
    AggregateState: Aqueous
    StandardThermoModel:
      Constant:
        G0: 0.0

  K+:
    Name: K+
    Formula: K+
    Elements: 1:K
    Charge: 1
    AggregateState: Aqueous
    StandardThermoModel:
      Constant:
        G0: 0.0
  
  NO3-:
    Name: NO3-
    Formula: NO3-
    Elements: 1:N 3:O
    Charge: -1
    AggregateState: Aqueous
    StandardThermoModel:
      Constant:
        G0: 0.0

  Ag+:
    Name: Ag+
    Formula: Ag+
    Elements: 1:Ag
    Charge: +1
    AggregateState: Aqueous
    StandardThermoModel:
      Constant:
        G0: 0.0
    
  Cu+2:
    Name: Cu+2
    Formula: Cu+2
    Elements: 1:Cu
    Charge: 2
    AggregateState: Aqueous
    StandardThermoModel:
      Constant:
        G0: 0.0

  Mn+2:
    Name: Mn+2
    Formula: Mn+2
    Elements: 1:Mn
    Charge: 2
    AggregateState: Aqueous
    StandardThermoModel:
      Constant:
        G0: 0.0
  
  Pb+2:
    Name: Pb+2
    Formula: Pb+2
    Elements: 1:Pb
    Charge: 2
    AggregateState: Aqueous
    StandardThermoModel:
      Constant:
        G0: 0.0
  
  Cl-:
    Name: Cl-
    Formula: Cl-
    Elements: 1:Cl
    Charge: -1
    AggregateState: Aqueous
    StandardThermoModel:
      Constant:
        G0: 0.0

  I-:
    Name: I-
    Formula: I-
    Elements: 1:I
    Charge: -1
    AggregateState: Aqueous
    StandardThermoModel:
      Constant:
        G0: 0.0
  
  NH3:
    Name: NH3
    Formula: NH3
    Elements: 3:H 1:N
    AggregateState: Aqueous
    StandardThermoModel:
      Constant:
        G0: 0.0
  
  S-2:
    Name: S-2
    Formula: S-2
    Elements: 1:S
    Charge: -2
    AggregateState: Aqueous
    StandardThermoModel:
      Constant:
        G0: 0.0

# Species from Formation Reactions
  H2O:
    Name: H2O
    Formula: H2O
    Elements: 2:H 1:O
    AggregateState: Aqueous
    FormationReaction:
      Reactants: 1:H+ 1:OH-
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 14.0
  
  NH4+:
    Name: NH4+
    Formula: NH4+
    Elements: 4:H 1:N
    Charge: 1
    AggregateState: Aqueous
    FormationReaction:
      Reactants: 1:NH3 1:H+
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 9.25
  
  HS-:
    Name: HS-
    Formula: HS-
    Elements: 1:H 1:S
    Charge: -1
    AggregateState: Aqueous
    FormationReaction:
      Reactants: 1:H+ 1:S-2
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 14.0
  
  H2S:
    Name: H2S
    Formula: H2S
    Elements: 2:H 1:S
    AggregateState: Aqueous
    FormationReaction:
      Reactants: 1:H+ 1:HS-
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 7.0

  AgCl(s):
    Name: AgCl(s)
    Formula: AgCl
    Elements: 1:Ag 1:Cl
    AggregateState: Solid
    FormationReaction:
      Reactants: 1:Ag+ 1:Cl-
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 9.75
  
  AgI(s):
    Name: AgI(s)
    Formula: AgI
    Elements: 1:Ag 1:I
    AggregateState: Solid
    FormationReaction:
      Reactants: 1:Ag+ 1:I-
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 16

  Ag2S(s):
    Name: Ag2S(s)
    Formula: Ag2S
    Elements: 2:Ag 1:S
    AggregateState: Solid
    FormationReaction:
      Reactants: 2:Ag+ 1:S-2
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 50.1

    
  Ag(NH3)+:
    Name: Ag(NH3)+
    Formula: Ag(NH3)+
    Elements: 3:H 1:N 1:Ag
    Charge: 1
    AggregateState: Aqueous
    FormationReaction:
      Reactants: 1:Ag+ 1:NH3
      ReactionStandardThermoModel:
        ConstLgK:
         lgKr: 3.32
  
  Ag(NH3)2+:
    Name: Ag(NH3)2+
    Formula: Ag(NH3)2+
    Elements: 6:H 2:N 1:Ag
    Charge: 1
    AggregateState: Aqueous
    FormationReaction:
      Reactants: 1:Ag(NH3)+ 1:NH3
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 3.92
  
  AgCl2-:
    Name: AgCl2-
    Formula: AgCl2-
    Elements: 2:Cl 1:Ag
    Charge: -1
    AggregateState: Aqueous
    FormationReaction:
      Reactants: 1:Ag+ 2:Cl-
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 5.25
  
  PbCl2(s):
    Name: PbCl2(s)
    Formula: PbCl2
    Elements: 1:Pb 2:Cl
    AggregateState: Solid
    FormationReaction:
      Reactants: 1:Pb+2 2:Cl-
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 4.77
  
  PbI2(s):
    Name: PbI2(s)
    Formula: PbI2
    Elements: 1:Pb 2:I
    AggregateState: Solid
    FormationReaction:
      Reactants: 1:Pb+2 2:I-
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 8.01
  
  PbS(s):
    Name: PbS(s)
    Formula: PbS
    Elements: 1:Pb 1:S
    AggregateState: Solid
    FormationReaction:
      Reactants: 1:Pb+2 1:S-2
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 27.5

  CuS(s):
    Name: CuS(s)
    Formula: CuS
    Elements: 1:Cu 1:S
    AggregateState: Solid
    FormationReaction:
      Reactants: 1:Cu+2 1:S-2
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 36.1
  
  MnS(s):
    Name: MnS(s)
    Formula: MnS
    Elements: 1:Mn 1:S
    AggregateState: Solid
    FormationReaction:
      Reactants: 1:Mn+2 1:S-2
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 13.5
      
  Cu(NH3)+2:
    Name: Cu(NH3)+2
    Formula: Cu(NH3)+2
    Elements: 3:H 1:N 1:Cu
    Charge: 2
    AggregateState: Aqueous
    FormationReaction:
      Reactants: 1:Cu+2 1:NH3
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 4.31

  Cu(NH3)2+2:
    Name: Cu(NH3)2+2
    Formula: Cu(NH3)2+2
    Elements: 6:H 2:N 1:Cu
    Charge: 2
    AggregateState: Aqueous
    FormationReaction:
      Reactants: 1:Cu(NH3)+2 1:NH3
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 3.67
  
  Cu(NH3)3+2:
    Name: Cu(NH3)3+2
    Formula: Cu(NH3)3+2
    Elements: 9:H 3:N 1:Cu
    Charge: 2
    AggregateState: Aqueous
    FormationReaction:
      Reactants: 1:Cu(NH3)2+2 1:NH3
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 3.04
  
  Cu(NH3)4+2:
    Name: Cu(NH3)4+2
    Formula: Cu(NH3)4+2
    Elements: 12:H 4:N 1:Cu
    Charge: 2
    AggregateState: Aqueous
    FormationReaction:
      Reactants: 1:Cu(NH3)3+2 1:NH3
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 2.30
  
  Cu(OH)2(s):
    Name: Cu(OH)2(s)
    Formula: Cu(OH)2
    Elements: 2:H 2:O 1:Cu
    AggregateState: Solid
    FormationReaction:
      Reactants: 1:Cu+2 2:OH-
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 19.32
  
  Pb(OH)2(s):
    Name: Pb(OH)2(s)
    Formula: Pb(OH)2
    Elements: 2:H 2:O 1:Pb
    AggregateState: Solid
    FormationReaction:
      Reactants: 1:Pb+2 2:OH-
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 19.84
  
  Mn(OH)2(s):
    Name: Mn(OH)2(s)
    Formula: Mn(OH)2
    Elements: 2:H 2:O 1:Mn
    AggregateState: Solid
    FormationReaction:
      Reactants: 1:Mn+2 2:OH-
      ReactionStandardThermoModel:
        ConstLgK:
          lgKr: 12.7

    

    